### ISSUE TITLE
Downsides of preferWheels?

### ISSUE THREAD

**Issue by zupo** [nix-community/poetry2nix#1032]
Not really an issue but more of a question: I often resort to using `preferWheels` to fix build problems. And I'm thinking why not use `preferWheels` by default. I've tried searching for documentation on the implications and can't find any, so I'm asking here: what are the downsides of using `preferWheels`, or in other words, what's preventing it from being enabled by default?

**Comment by njaremko** [comment]
Wheels are pre-built blobs, which means your bypassing `nix`, and not building from source, which is the general preference across the nix ecosystem

**Comment by zupo** [comment]
Thanks!
