### ISSUE TITLE
Binary cache for poetry2nix builds

### ISSUE THREAD

**Issue by energizah** [nix-community/poetry2nix#104]
Some Python packages take a while to build, such as numpy, scipy, etc. It would be nice if that build time could be reduced as much as possible by having Hydra build them in advance.

I think the matrix would be (package version, nixpkgs version, platform) and it's hard to say in advance of trying it how much sharing there will be. Maybe I'm missing a couple dimensions. But I wouldn't be surprised if, say, (current package version, nixos-unstable, linux x86-64) was a useful combination for a good number of users of popular packages.

I'm not sure what's involved in making this happen but I figured I'd start the conversation. (Happy to move it elsewhere if there's a better place.)

**Comment by adisbladis** [comment]
I would love to see more caching of packages built with `poetry2nix`!
However, I think the best way to achieve that is to move packages in nixpkgs over to using `poetry2nix`.

That way it ends up in the official binary cache and is immediately useful to way more people than if we used the nix-community cache.

**Comment by mtn** [comment]
@adisbladis What needs to happen for this to become reality?

**Comment by mtn** [comment]
Also, simple question: why aren't binaries from pypi pulled in here?

**Comment by adisbladis** [comment]
> Also, simple question: why aren't binaries from pypi pulled in here?

Because we default to build from source, both for purity reasons and for flexibility.

**Comment by adisbladis** [comment]
> What needs to happen for this to become reality?

Someone needs to put in the work.

**Comment by adisbladis** [comment]
I'm gonna close this for now as I don't see anything that can be done in the context of `poetry2nix` itself.

**Comment by mtn** [comment]
> > What needs to happen for this to become reality?
> 
> Someone needs to put in the work.

Could you be a bit more specific? I think this would be really nice, but I'm not sure how to start working on something like this
