### ISSUE TITLE
poetry2nix breaks on these two applications

### ISSUE THREAD

**Issue by dhess** [nix-community/poetry2nix#107]
https://github.com/benkehoe/aws-sso-credential-process
https://github.com/benkehoe/aws-export-credentials

I don't know much about Poetry, so I'm not sure whether these packages include "proper" Poetry packaging, but they break `poetry2nix.mkPoetryApplication` in the following ways:

1. They don't provide a `poetry.lock` file.
2. `mkPoetryApplication` can't seem to find their included `pyproject.toml` files.
3. They don't provide a homepage attribute, which causes `mkPoetryApplication` in nixpkgs to break when evaluated on a Hydra:

```
attribute 'homepage' missing, at /nix/store/4rhbxlzypnbn1ia258czb2s806dw3xj9-source/pkgs/development/tools/poetry2nix/poetry2nix/default.nix:225:27
```

I was able to work around these by creating `pyproject.toml` and `poetry.lock` files in the Nix packaging for these 2 applications, but is that the way it's meant to work? It would be nice if the homepage attribute were not required and `poetry.lock` could be generated automatically, in any case.

**Comment by dhess** [comment]
FYI, here's how I got these to work in my overlay:

https://github.com/hackworthltd/hacknix/tree/master/pkgs/aws-export-credentials
https://github.com/hackworthltd/hacknix/tree/master/pkgs/aws-sso-credential-process

I had to add the `homepage` attribute to `aws-export-credentials`'s `pyproject.toml` file here:

https://github.com/hackworthltd/hacknix/blob/8271511bc9a546c95e27a91a8a52693c2a6efdf6/pkgs/aws-export-credentials/pyproject.toml#L7

despite the fact that the `default.nix` provides a `meta.homepage` attribute. Hydra would not evaulate the package until I added it to the `pyproject.toml` file.

**Comment by adisbladis** [comment]
I think https://github.com/nix-community/poetry2nix/pull/108 should have fixed this. Thanks for reporting!
