### ISSUE TITLE
Build using 'grafana_api' python package failing due to missing 'git' command 

### ISSUE THREAD

**Issue by tewfik-ghariani** [nix-community/poetry2nix#109]
Hello @adisbladis,

Not really sure if this is the right place to report this but I cannot tell for sure what is the root cause and on which level should we fix it 

But here is the situation :

I'm trying to build a nixops-grafana plugin using poetry2nix as dependency manager.
For this plugin, I need to use a python module called '[grafana_api](https://github.com/m0nhawk/grafana_api.git)' and hence add it in the pyproject.toml config file as shown here ( tried both the following alternatives but the output is the same ) 

```
[tool.poetry.dependencies]
python = "^3.7.6"
grafana-api = {git = "https://github.com/m0nhawk/grafana_api.git", rev = "master"}
#grafana-api = "1.0.2"
```
Whenever I work locally using `poetry shell`, I encounter no issues at all and I'm able to use all python dependencies.

However, whenever I try to build nixops-grafana, it fails with this error
```
unpacking source archive /nix/store/ximp6z9w9w10f4jiilfq47wi261s4h0b-source
source root is source
setting SOURCE_DATE_EPOCH to timestamp 315619200 of file source/test/test_grafana.py
patching sources
configuring
no configure script, doing nothing
building
Executing setuptoolsBuildPhase
Traceback (most recent call last):
  File "setup.py", line 8, in get_version
    ["git", "describe", "--tags", "--abbrev=0", "--match=[0-9]*"]
  File "/nix/store/55b9ip7xkpimaccw9pa0vacy5q94f5xa-python3-3.7.6/lib/python3.7/subprocess.py", line 411, in check_output
    **kwargs).stdout
  File "/nix/store/55b9ip7xkpimaccw9pa0vacy5q94f5xa-python3-3.7.6/lib/python3.7/subprocess.py", line 488, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/nix/store/55b9ip7xkpimaccw9pa0vacy5q94f5xa-python3-3.7.6/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/nix/store/55b9ip7xkpimaccw9pa0vacy5q94f5xa-python3-3.7.6/lib/python3.7/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'git': 'git'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "nix_run_setup", line 8, in <module>
    exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\\r\\n', '\\n'), __file__, 'exec'))
  File "setup.py", line 24, in <module>
    version=get_version(),
  File "setup.py", line 13, in get_version
    "The version number cannot be extracted from git tag in this source "
RuntimeError: The version number cannot be extracted from git tag in this source distribution; please either download the source from PyPI, or check out from GitHub and make sure that the git CLI is available.
builder for '/nix/store/nax1x07nq206hazqb2n5ykcfcs6q8hsg-python3.7-grafana-api-1.0.2.drv' failed with exit code 1
cannot build derivation '/nix/store/rm1afdnm6g20y8n2r180xlyhn1zrapr7-nixops_grafana-1.0.drv': 1 dependencies couldn't be built
error: build of '/nix/store/rm1afdnm6g20y8n2r180xlyhn1zrapr7-nixops_grafana-1.0.drv' failed
```
Full logs : https://github.com/tewfik-ghariani/nixops-grafana/runs/691507349

This appears to be a specific way to fetch the 'version' for this particular python module

```python
def get_version():
    try:
        tag = check_output(
            ["git", "describe", "--tags", "--abbrev=0", "--match=[0-9]*"]
        )
        return tag.decode("utf-8").strip("\n")
```

https://github.com/m0nhawk/grafana_api/blob/master/setup.py#L5

How to work around this? How to include 'git' in the build runtime? Is this a poetry issue or something else?

Any assistance is much appreciated!
Thanks

**Comment by adisbladis** [comment]
Hey!

I'd recommend adding an override in the same style as https://github.com/nix-community/poetry2nix/blob/master/overrides.nix#L828-L835.
It would look like
``` nix
grafana_api = super.grafana_api.overridePythonAttrs(old: {
  postPatch = ''
    substituteInPlace setup.py --replace 'version=get_version()' 'version="${old.version}"'
  '';
});
```

**Comment by tewfik-ghariani** [comment]
Thanks for the follow up! I tried that per https://github.com/tewfik-ghariani/nixops-grafana/commit/6a3c2eced8322837d36615f3a6d9d4c71148826f but unfortunately it did not solve the issue
The build is still failing : https://github.com/tewfik-ghariani/nixops-grafana/runs/700991979

Did I miss something?

**Comment by tewfik-ghariani** [comment]
Your PR consisting in correcting the package name solved the problem :  https://github.com/tewfik-ghariani/nixops-grafana/pull/2

Thanks again! 

Closing,
