### ISSUE TITLE
`pandas` `2.0.0` requires `versioneer[toml]` for its build

### ISSUE THREAD

**Issue by JonBoyleCoding** [nix-community/poetry2nix#1127]
### Describe the issue

Pandas 2.0.0 has an updated build using `versioneer[toml]`:

https://github.com/pandas-dev/pandas/blob/eb9a3e81a946d5921e4458632e9632239ac8e8d1/pyproject.toml#L4-L10

```toml
requires = [
    "setuptools>=61.0.0",
    "wheel",
    "Cython>=0.29.33,<3",  # Note: sync with setup.py, environment.yml and asv.conf.json
    "oldest-supported-numpy>=2022.8.16",
    "versioneer[toml]"
]
```

I've tried updating it myself however this doesn't work as it complains it cannot find `versioneer[toml]`

https://github.com/JonBoyleCoding/poetry2nix/blob/9b5580ca8fd058991d532b377e6a61ea072d86a9/overrides/build-systems.json#L10711-L10718

```json
  "pandas": [
    "cython",
    "setuptools",
    {
      "buildSystem": "versioneer[toml]",
      "from": "2.0.0"
    }
  ],
```
How can this be done? Or is it a current limitation of the project? Thanks.

**Comment by silky** [comment]
Bumped into this today.

Fwiw I think a fix is to use the [`passthru`-style](https://github.com/NixOS/nixpkgs/blob/master/doc/languages-frameworks/python.section.md#optional-extra-dependencies-python-optional-dependencies) in the package definition itself; see for example twisted: https://github.com/NixOS/nixpkgs/blob/nixos-22.11/pkgs/development/python-modules/twisted/default.nix#L143

I think with that; then _maybe_ you could change the build-system statement to be:

```
  "pandas": [
    "cython",
    "setuptools",
    {
      "buildSystem": "versioneer",
      "from": "2.0.0"
    },
    {
      "buildSystem": "versioneer.passthru.optional-dependencies.toml",
      "from": "2.0.0"
    }
  ],
```

and it would work ... this is just a guess, I haven't had time to test it.
