### ISSUE TITLE
Auto-tag releases after every PR merge

### ISSUE THREAD

**Issue by l0b0** [nix-community/poetry2nix#1197]
### Describe the issue

This scenario happens pretty frequently:

1. Someone releases their package with a new undeclared build dependency.
2. Dependabot or Renovate bumps the package in my repos.
3. The builds break because the poetry2nix in stable nixpkgs does not have the relevant override.
4. Checking the poetry2nix repo, it turns out the override is already in the master branch, it just hasn't been released yet. Since I use [nixpkgs pinning](https://nixos.wiki/wiki/FAQ/Pinning_Nixpkgs), usually to a nixos-XX.YY branch, I have two choices:
    1. wait for a new release to get to that channel then bump nixpkgs, or
    2. manually copy across the override, then remove the override after upgrading poetry2nix.

Option 1 is preferable if the wait time is small, but there's usually [a long time between releases](https://github.com/nix-community/poetry2nix/tags). Option 2 is much more complex and time-consuming.

A solution would be to automatically tag a poetry2nix release after every merge to master. The nixpkgs bots should pick up this change pretty quickly, and within hours or a handful of days the new poetry2nix version should be available in all the nixpkgs channels.

This would help a lot with packages with complex overrides and frequent updates, like [cryptography](https://github.com/nix-community/poetry2nix/issues/413).

### Additional context

From a chat with @adisbladis:

> I thought about making releases use calver instead and auto tag them on master
> I don't have time to work on this myself rn, but I'd be very happy to accept a PR adding it
> In the mean time I've tagged a new release

So if you have time to implement this, please go ahead.

**Comment by adisbladis** [comment]
Closed in 52850e7d53744ab1c33dbdbe17379f3bd22c1a54

**Comment by adisbladis** [comment]
I'm debating whether to run this as a cron job instead so that it's _also_ reasonable to automatically send a PR to nixpkgs.
Probably weekly.
