### ISSUE TITLE
grafana-api substituteInPlace setup.py is not working for ci/shell.nix

### ISSUE THREAD

**Issue by tewfik-ghariani** [nix-community/poetry2nix#123]
Hello @adisbladis  :)

This issue is almost the same as #109 but this time it is related to the shell.nix ci script related to grafana-api

The github actions spawn a nix-shell using the [shell.nix](https://github.com/tewfik-ghariani/nixops-grafana/blob/master/ci/shell.nix) script in order to run the ci tests

That being said, all workflows are failing during the *Prefetch shell.nix* action due to 2 problems

1) Python 3.7 is used instead of python 3.8

```ERROR: Could not find a version that satisfies the requirement importlib-metadata>=0.12; python_version < "3.8" (from pluggy==0.13.1) (from versions: none)
ERROR: No matching distribution found for importlib-metadata>=0.12; python_version < "3.8" (from pluggy==0.13.1)
builder for '/nix/store/f39wxy6d1vvm4ggs34p6244ji97ywq97-python3.7-pluggy-0.13.1.drv' failed with exit code 1
cannot build derivation '/nix/store/rxddmhwa9slwjqyz81d5akv732pfi9j7-python3-3.7.7-env.drv': 1 dependencies couldn't be built
error: build of '/nix/store/rxddmhwa9slwjqyz81d5akv732pfi9j7-python3-3.7.7-env.drv' failed
```
More logs : https://github.com/tewfik-ghariani/nixops-grafana/runs/759122635

Forcing the python version fixed the problem locally but the issue remains in github runners
```
    (pkgs.poetry2nix.mkPoetryEnv {
      projectDir = ../.;
      python = pkgs.python38;
```
https://github.com/tewfik-ghariani/nixops-grafana/blob/master/ci/shell.nix#L8

2) Once the python version issue is fixed locally, came across another one consisting in the same problem described per #109 . Once I added the workaround you recommended, it failed for a different error : 
```
patching sources
configuring
no configure script, doing nothing
building
Executing setuptoolsBuildPhase
Traceback (most recent call last):
  File "nix_run_setup", line 8, in <module>
    exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\\r\\n', '\\n'), __file__, 'exec'))
  File "/nix/store/m9g361va65ccbj2v5nil4dfr194zgarn-python3-3.8.3/lib/python3.8/tokenize.py", line 392, in open
    buffer = _builtin_open(filename, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'setup.py'
builder for '/nix/store/ysx3xs36d2bwpw757idrpx2xlsx3x79l-python3.8-nixops-1.8.0.drv' failed with exit code 1
cannot build derivation '/nix/store/js6nl6bwlb6wf7cv4lw5jyyrrbk98810-python3-3.8.3-env.drv': 1 dependencies couldn't be built
error: build of '/nix/store/js6nl6bwlb6wf7cv4lw5jyyrrbk98810-python3-3.8.3-env.drv' failed
```

Can you help please suggest what is the best approach to resolve the failed github jobs?

**Comment by tewfik-ghariani** [comment]
Any idea? @adisbladis

**Comment by mickours** [comment]
I just add the same problem with `pluggy` and I found out that it comes from importlib-metadata version which is not defined in the [setup.cfg file](https://github.com/python/importlib_metadata/blob/master/setup.cfg#L1). This leads to a rendered version of 0.0.0 which make the dependencies solver fails.

I've had the same problem with `pytest` recently and found this override that fixed the problem https://github.com/nix-community/poetry2nix/issues/188#issuecomment-720145425

Applying the same override to `importlib-metadata` fixed the problem:
```nix
let
overrides = poetry2nix.overrides.withDefaults (self: super: {
  importlib-metadata = super.importlib-metadata.overrideAttrs (old: {
      postPatch = old.postPatch or "" + ''
        sed -i '/\[metadata\]/aversion = ${old.version}' setup.cfg
      '';
    });
});
in
 poetry2nix.mkPoetryApplication {
    projectDir = ./.;
    inherit overrides;
 }
```

**Comment by tewfik-ghariani** [comment]
@mickours  Thank you so much for sharing :+1: 

I believe this is no longer an issue since I got rid of the 'Prefetch' phase after upgrading the `install-nix-action` github action's version. As a result, the aforementioned errors are no longer shown in the CI builds

Ref : https://github.com/tewfik-ghariani/nixops-grafana/commit/384e1613071369f1b64fb8424e5d8a70e8717232

Closing,
