### ISSUE TITLE
Handle git dependencies

### ISSUE THREAD

**Issue by zimbatm** [nix-community/poetry2nix#13]
`pyproject.toml` can contain a dependency like:
```toml
requests = { git = "https://github.com/psf/requests.git", branch = "master" }
```
which translates to an entry like:

`poetry.lock`
```toml
[[package]]                                                                   
category = "main"                                                             
description = "Python HTTP for Humans."                                       
name = "requests"                                                             
optional = false                                                              
python-versions = ">=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*, !=3.4.*"        
version = "2.22.0"                                                            
                                                                              
[package.dependencies]                                                        
certifi = ">=2017.4.17"                                                       
chardet = ">=3.0.2,<3.1.0"                                                    
idna = ">=2.5,<2.9"                                                           
urllib3 = ">=1.21.1,<1.25.0 || >1.25.0,<1.25.1 || >1.25.1,<1.26"              
                                                                              
[package.extras]                                                              
security = ["pyOpenSSL (>=0.14)", "cryptography (>=1.3.4)", "idna (>=2.0.0)"] 
socks = ["PySocks (>=1.5.6,<1.5.7 || >1.5.7)", "win-inet-pton"]               
                                                                              
[package.source]                                                              
reference = "eedd67462819f8dbf8c1c32e77f9070606605231"                        
type = "git"                                                                  
url = "https://github.com/psf/requests.git" 
```

It's not ideal but this could be translated to:
```nix
builtins.fetchgit { url = "https://github.com/psf/requests.git"; rev = "eedd67462819f8dbf8c1c32e77f9070606605231"; }
```

**Comment by FRidh** [comment]
What is not ideal about it? That the branch is not mentioned in the lock file? Or that we need to do a full clone?

**Comment by zimbatm** [comment]
The main issue is that builtins fetchers are not available in all scenarios. For example in Hydra, poetry2nix projects would work until somebody adds a git dependency.

**Comment by FRidh** [comment]
Yes, that's an issue. I think it's an issue with these builtin functions that we do not mark whether they fetch expressions or other artifacts. If we would do that, then there wouldn't be a problem anymore.

**Comment by zimbatm** [comment]
The core issue is that the lockfile doesn't contain the `sha256` needed by `pkgs.fetchGit`. The folder hashing algorithm of nix is non-standard so it will be hard to convince upstream to add it to the lockfile. This is an issue that is not unique to poetry2nix and that we have across all language integrations.

One possible resolution, if the output of `git archive` is stable, is to use that as the sha256 input. `git archive HEAD | sha256sum | cut -d' ' -f1`
Maybe it's possible to convince upstream to add that to their lockfile on the basis that a pre-image attack on the git sha1 exists[1].
And then add a `pkgs.fetchGitArchive` to nixpkgs.

[1]: http://shattered.io/

**Comment by zimbatm** [comment]
it looks like the archive time is the current time if the reference is not a git tag:
https://github.com/git/git/blob/b02fd2accad4d48078671adf38fe5b5976d77304/archive.c#L403-L410
which is consistent with the documentation.

So git would first have to be extended to provide a stable output format.

**Comment by FRidh** [comment]
I think efforts are better put into making `builtins.fetchGit` suitable for fetching non-expressions than trying to get something to work with `pkgs.fetchGit` because of the auth mess in case of private repo's.

**Comment by adisbladis** [comment]
Git is implemented in https://github.com/nix-community/poetry2nix/pull/21 which is somewhat based on https://github.com/nix-community/poetry2nix/pull/19
