### ISSUE TITLE
Infinite recursion & runaway memory usage

### ISSUE THREAD

**Issue by PAI5REECHO** [nix-community/poetry2nix#1316]
### Describe the issue
This Flake is causing some crazy memory usage. There's some sort of infinite recursion going on in the default Flake template:
```sh
$ docker run --rm -it --net host nixos/nix:2.18.0pre20230914_2a52ec4
bash-5.1# mkdir ./test/ && cd ./test/
bash-5.1# nix --extra-experimental-features 'nix-command flakes' flake init -t github:nix-community/poetry2nix
bash-5.1# git init && git add -A
bash-5.1# nix --extra-experimental-features 'nix-command flakes' develop
```
![flamegraph](https://github.com/nix-community/poetry2nix/assets/96688573/43dd0fe7-a1bf-4fa1-8d15-fedde45d8b5b)

**Comment by benley** [comment]
I'm able to reproduce this as well.  Do you know of a workaround?

**Comment by benley** [comment]
this is probably related to #1291

**Comment by revol-xut** [comment]
I think I am running into the same problem. A `nix flake check` is just not terminating on the template flake until it gets shutdown by my watchdog.

**Comment by rbozan** [comment]
Same

**Comment by FRidh** [comment]
> this is probably related to #1291

This can occur even when evaluating against nixos 23.05.

**Comment by mausch** [comment]
First time trying to use poetry2nix and I ran into this. Don't know if this happens with all projects?
Repro:

```
$ git clone https://github.com/langchain-ai/langchain/
$ cd langchain
$ nix flake init --template github:nix-community/poetry2nix  # as documented in https://github.com/nix-community/poetry2nix#using-the-flake
$ nix develop
```
