### ISSUE TITLE
How to add additional python packages to generated pythonEnv

### ISSUE THREAD

**Issue by matthuszagh** [nix-community/poetry2nix#144]
I'm attempting to create a python environment for a python package for which 2 of the dependencies are only available from nixpkgs python packages (not poetry). The rest of the dependencies are specified as part of `pyproject.toml` and `poetry.lock` files. Is there a way to add extra packages to the environment created by `mkPoetryEnv`? I'm currently using the following expression:

```nix
pythonEnv = pkgs.poetry2nix.mkPoetryEnv {
  projectDir = ./.;
  python = pkgs.python3;
};
```

Of course this doesn't work, but what I'm shooting for is something like this:

```nix
pythonEnv = pkgs.poetry2nix.mkPoetryEnv {
  projectDir = ./.;
  python = pkgs.python3;
  extraLibs = (with openems-pkgs.python3.pkgs; [
    python-openems
    python-csxcad
  ]);
};
```

I've tried various overrides but haven't yet found something that works.

**Comment by adisbladis** [comment]
This is not supported and I don't think I will add it. You could probably install these from their respective Git repositories if they are not on PyPi?

**Comment by matthuszagh** [comment]
Unfortunately, pointing to a git repo doesn't really help. Their cython build process relies on a system installation of several C++ libraries, which is [why the developer never made them available on PyPi](https://github.com/thliebig/openEMS/issues/72#issuecomment-672220569). This is trivial to do with Nix, of course, since I can provide these libraries as dependencies and indicate where they can be found. See [this line](https://github.com/matthuszagh/nixpkgs/blob/6b8a978a80e863c6f164fe199b8cd7c616da1639/pkgs/development/python-modules/python-openems/default.nix#L33) of my Nix build expression. Is there a way to achieve something similar with poetry2nix?

I'm working to get these modules packages for PyPi, but I'm not experienced in python packaging and these cases are really non-trivial. The library dependencies use cmake and have their own complex network of dependencies. The projects are [openems](https://github.com/thliebig/openEMS) and [csxcad](https://github.com/thliebig/CSXCAD), with the python information located in the python subdirectories of each project.

**Comment by adisbladis** [comment]
> See this line of my Nix build expression. Is there a way to achieve something similar with poetry2nix?

Absolutely there is!
```nix
self: super: {
  packageName = super.packageName.overridePythonAttrs(old: {
    format = "setuptools";
    setupPyBuildFlags = "-I${openems}/include -L${openems}/lib -R${openems}/lib";
  });
}
```

**Comment by matthuszagh** [comment]
Thanks for the prompt response! This looks to be exactly what I was hoping for. Still having a bit of trouble though... here's what I've got
```nix
let
  pkgs = (import (builtins.fetchTarball {
    name = "matthuszagh-nixpkgs-unstable-2020-08-10";
    url = "https://github.com/matthuszagh/nixpkgs/archive/6b8a978a80e863c6f164fe199b8cd7c616da1639.tar.gz";
    sha256 = "173i1sms6j3waiab2108nbxjqwmbsjdz8v6ymkmgipg80mxjkx30";
  }) {
  overlays = [
    (self: super: {
      poetry2nix = super.poetry2nix.overrideScope' (p2nixself: p2nixsuper: {
        defaultPoetryOverrides = p2nixsuper.defaultPoetryOverrides.extend (pyself: pysuper: {
          CSXCAD = pysuper.CSXCAD.overridePythonAttrs(oldAttrs: {
            format = "setuptools";
            setupPyBuildFlags = "-I${super.openems}/include -L${super.openems}/lib -R${super.openems}/lib";
          });
          openEMS = pysuper.openEMS.overridePythonAttrs(oldAttrs: {
            format = "setuptools";
            setupPyBuildFlags = "-I${super.openems}/include -L${super.openems}/lib -R${super.openems}/lib";
          });
        });
      });
    })
  ];
  });
  env = pkgs.poetry2nix.mkPoetryEnv {
    projectDir = ./.;
  };
in
pkgs.mkShell {
  buildInputs = [
    env
  ];
}

```

but i get the following error:
```
matt@ryzen3950 ~/s/pyems (master) [1]> nix-shell
error: --- SysError ------------------------------------------------------------------------------------------------------------------------------------- nix-shell
opening file '/home/matt/src/CSXCAD/python/pyproject.toml': No such file or directory
(use '--show-trace' to show detailed location information)
```

Indeed there is no `pyproject.toml` in that directory, just a `setup.py` file, but I was under the impression that's what `format = "setuptools"` did.

if I change the above to `mkPoetryApplication` I get the same error.

Where am I going wrong here? If it's helpful, here's my pyproject.toml too:
```
[tool.poetry]
name = "py-ems"
version = "0.1.0"
description = "High-level python interface to OpenEMS with automatic mesh generation"
authors = ["Matt Huszagh <huszaghmatt@gmail.com>"]
packages = [
    {include = "pyems"}
]

[tool.poetry.dependencies]
python = "^3.8"
numpy = "^1.19.1"
scipy = "^1.5.2"
openems = { path = "../openEMS-Project/openEMS/python" }
csxcad = { path = "../CSXCAD/python" }
setuptools = "^49.6.0"

[tool.poetry.dev-dependencies]
cython = "^0.29.21"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
```
