### ISSUE TITLE
Attribute 'buildInputs' missing at overrides.nix

### ISSUE THREAD

**Issue by aswan89** [nix-community/poetry2nix#153]
Contents of `shell.nix`
```
{ pkgs ? import <nixpkgs> {} }:                                       
let                                                                   
  app = pkgs.poetry2nix.mkPoetryEnv {                                 
    python = pkgs.python37;                                           
    projectDir = ./.;                                                 
    overrides = pkgs.poetry2nix.overrides.withDefaults (self: super: {                                                
      h3 = super.h3.overridePythonAttrs(oldAttrs: {                   
        buildInputs = (oldAttrs.buildInputs or []) ++ [               
          self.scikit-build                                           
        ];                                                            
      });                                                             
    });                                                               
  };                                                                  
in pkgs.mkShell {                                                     
  buildInputs = [                                                     
    app                                                               
  ];                                                                  
}                                                                     
```

Running `nix-shell` returns this error: `error: attribute 'buildInputs' missing, at /nix/store/n12pmyn5ijpcf6zz1wspiw1fqrbm91wj-nixpkgs-20.09pre238994.078b9f8aa68/nixpkgs/pkgs/development/tools/poetry2nix/poetry2nix/overrides.nix:613:21
(use '--show-trace' to show detailed location information)`

If I investigate the line in `overrides.nix` the error message points to it shows the default override for `pyopenssl`. My interpretation is that the `default.nix` for `pyopenssl` within [`nixos-unstable`](https://github.com/NixOS/nixpkgs-channels/blob/16fc531784ac226fb268cc59ad573d2746c109c1/pkgs/development/python-modules/pyopenssl/default.nix#L109) uses `nativeBuildInputs` rather than `buildInputs` and as such the default override is attempting to extend an attribute that does not exist. I'm not knowledgeable enough about the interactions between the various `*BuildInputs` to know if that should matter or not though. I cribbed the override pattern of `(oldAttrs.buildInputs or [])` from some other bit of documentation and it may or may not be good practice for the default overrides. 

In the mean time, I've been experimenting with trying to override the default override for `pyopenssl` without any luck. Is that type of thing supported?

**Comment by ryneeverett** [comment]
I don't think this particular bug can be reproduced without either the corresponding `pyproject.toml` or `poetry.lock`. However, this class of bugs would seem to be resolved by the `old.buildInputs or []` pattern. I ran into the same issue with cffi and was able to work around it by forking poetry2nix and applying the pattern to `overrides.nix`.

Applying the  `old.buildInputs or []` pattern throughout `overrides.nix` would resolve this entire class of bugs but surely that's not the right solution. It appears that the packages being overridden are not from nixpkgs but constructed by template on the fly, so I don't understand how they would fail to have a `buildInputs` attribute.

**Comment by adisbladis** [comment]
Fixed in https://github.com/nix-community/poetry2nix/pull/250.

All bundled overrides should now be safe against missing attributes.
