### ISSUE TITLE
scipy v1.13  requires cython 3

### ISSUE THREAD

**Issue by nim65s** [nix-community/poetry2nix#1593]
according to ref https://github.com/scipy/scipy/commit/09401057668f2fae6916373b9751ea131f86916d

so we should change this https://github.com/nix-community/poetry2nix/blob/3c92540611f42d3fb2d0d084a6c694cd6544b609/overrides/build-systems.json#L18450

**Comment by TyberiusPrime** [comment]
I believe this has been done and can be closed.
overrides/build-systems.toml reads right now
```
"scipy": [
    "pybind11",
    "pythran",
    "setuptools",
    "wheel",
    {
      "buildSystem": "cython_0",
      "until": "1.12.0"
    },
    {
      "buildSystem": "cython",
      "from": "1.12.0"
    }
  ],

```
