### ISSUE TITLE
Can't install python-magic wheel

### ISSUE THREAD

**Issue by knkski** [nix-community/poetry2nix#1629]
### Describe the issue

`python-magic` fails to install when using `preferWheels = true;`. Setting this override in `shell.nix` lets it install properly:

```nix
python-magic = super.python-magic.override { preferWheel = false; };
```

The error message:

```
Sourcing python-remove-tests-dir-hook
Sourcing python-catch-conflicts-hook.sh
Sourcing python-remove-bin-bytecode-hook.sh
Sourcing wheel setup hook
Using wheelUnpackPhase
Sourcing pypa-install-hook
Using pypaInstallPhase
Sourcing python-imports-check-hook.sh
Using pythonImportsCheckPhase
Sourcing python-namespaces-hook
Sourcing python-catch-conflicts-hook.sh
@nix { "action": "setPhase", "phase": "unpackPhase" }
Running phase: unpackPhase
Executing wheelUnpackPhase
Finished executing wheelUnpackPhase
@nix { "action": "setPhase", "phase": "patchPhase" }
Running phase: patchPhase
substitute(): ERROR: file 'magic/loader.py' does not exist
```

It looks like this is due to poetry2nix attempting to [patch a file](https://github.com/nix-community/poetry2nix/blob/d2993e376bffc1669055197e41e687f9d1e303f4/overrides/default.nix#L2863) and that file doesn't exist. The file exists in the 0.4.27 wheel that I downloaded, so I'm not sure why the `postPatch` override is failing. 

### Additional context

`pyproject.toml`:

_Not explicitly listed, comes as dependency of `unstructured`_

`poetry.lock`:
```toml
# ... snip rest of file ...
[[package]]
name = "python-magic"
version = "0.4.27"
description = "File type identification using libmagic"
category = "main"
optional = false
python-versions = ">=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*, !=3.4.*"
files = [
    {file = "python-magic-0.4.27.tar.gz", hash = "sha256:c1ba14b08e4a5f5c31a302b7721239695b2f0f058d125bd5ce1ee36b9d9d3c3b"},
    {file = "python_magic-0.4.27-py2.py3-none-any.whl", hash = "sha256:c212960ad306f700aa0d01e5d7a325d20548ff97eb9920dcd29513174f0294d3"},
]
# ... snip rest of file ...
```

**Comment by cpcloud** [comment]
> The file exists in the 0.4.27 wheel that I downloaded

Indeed, but you also specify 

> python-magic = super.python-magic.override { preferWheel = false; };

which will attempt to build `python-magic` from source and will not use wheels. Similarly for #1628.

Will take a look at what's happening here.
