### ISSUE TITLE
sphinx-rtd-theme: missing override but package present in nix, can we compose ?

### ISSUE THREAD

**Issue by teto** [nix-community/poetry2nix#166]
so I hit the following issue:
```
  Building wheel for sphinx-rtd-theme (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /nix/store/fjgnz0xfl04hsblsi4ym5y5akfh6mlmy-python3-3.8.5/bin/python3.8 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/build/pip-req-build-kehc93tz/setup.py'"'"'; __file__='"'"'/build/pip-req-build-kehc93tz/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /build/pip-wheel-z9yzgf9_
       cwd: /build/pip-req-build-kehc93tz/
  Complete output (4 lines):
  running bdist_wheel
  running build
  running build_py
  error: [Errno 2] No such file or directory: 'npm'
  ----------------------------------------
  ERROR: Failed building wheel for sphinx-rtd-theme
  Running setup.py clean for sphinx-rtd-theme
```
Looks like npm is needed https://github.com/readthedocs/sphinx_rtd_theme/blob/38c30bf8ac99f648aef15907c623648739f373de/setup.py#L22
I tried adding nodejs to buildInputs to no avail, before finding out sphinx_rtd_theme was already packaged thus I did
```
  myPythonEnv = pkgs.poetry2nix.mkPoetryEnv {
    projectDir = ./.;
    overrides = pkgs.poetry2nix.overrides.withDefaults (self: super: {
      sphinx-rtd-theme = super.sphinx_rtd_theme;
    });
  };
```
doing so I think I skip the poetry generation system thus I wonder if I should instead submit a PR with an override that ends up closing the gap with the nixpkgs package ?

**Comment by adisbladis** [comment]
> doing so I think I skip the poetry generation system

No, you are not skipping the generation of packages. `super` refers to the generated set.

**Comment by teto** [comment]
I meant for this package. I wonder if poetry2nix could not merge some nix attributes with the generated ones. Probably bound to fail anyway :)

**Comment by teto** [comment]
quickfix seems to work fine but does not warrant a PR IMO. Closing.
