### ISSUE TITLE
psycopg2 & psycopg2-binary bytecode collision

### ISSUE THREAD

**Issue by aniinbkln** [nix-community/poetry2nix#1687]
I'm trying to install psycopg2 in my environment from the `pyproject.toml` file, but am getting an error while building the environment:

```nix
error: builder for '/nix/store/6y9hvhw2i2nfhdggr9nxda5zzm8pcc5l-python3-3.10.14-env.drv' failed with exit code 25;
       last 1 log lines:
       > error: collision between `/nix/store/gqxbzcqlhr4dlddqyskqkh1ma9nxzq02-python3.10-psycopg2-binary-2.9.9/lib/python3.10/site-packages/psycopg2/__pycache__/_ipaddress.cpython-310.pyc' and `/nix/store/33fwnhyndwdmswpjhvjhvhgydc8ipjka-python3.10-psycopg2-2.9.9/lib/python3.10/site-packages/psycopg2/__pycache__/_ipaddress.cpython-310.pyc'
```

Truncated view:

```nix
/.../psycopg2-binary-2.9.9/.../psycopg2/__pycache__/_ipaddress.cpython-310.pyc and
/.../psycopg2-2.9.9/.../psycopg2/__pycache__/_ipaddress.cpython-310.pyc
```
I use `defaultPoetryOverrides.extends` to already override some packages, and AFAIK this should come bundled with the upstream fixes for psycopg2 and psycopg2-binary. I also looked at #220 but the `override` attribute for `ignoringCollisions` seems to exist on `buildEnv`. 

Note that I am building on `darwin-aarch64` FWIW, and I haven't tried a linux build yet.

`flake.nix`:
```nix
myPyEnv = mkPoetryEnv {
          python = pkgs.python310;
          projectDir = ./;
          preferWheels = true; #workaround building rust deps
          overrides =
            defaultPoetryOverrides.extend
            (final: prev: {
              ...
            });
        };
```

`pyproject.toml`:
```toml
psycopg2 = "^2.9.9" 
```

The above error is reproducible with just this, but I really started with this:

 `pyproject.toml`:
```toml
psycopg2  = {extras = ["binary", "pool"], version="^2.9.9"}
```

Any insight or feedback is appreciated. Thank you so much for supporting this awesome tool!

**Comment by cpcloud** [comment]
Your example isn't fully reproducible. You need to include whatever's being overridden, because just building the psycopg2 package from source or using the binary wheel both build fine in isolation.

**Comment by aniinbkln** [comment]
@cpcloud you correctly called out the issue. Unfortunately, I cannot share the overridden packages since the repos are private, but I wanted to let you know I worked around it by building a poetry application and then adding that to the environment. Thank you for your help!
