### ISSUE TITLE
orjson 3.10.6 sha256 not defined

### ISSUE THREAD

**Issue by jchan-legendpower** [nix-community/poetry2nix#1722]
### Describe the issue
orjson dependency is not defined for version 3.10.6 leading to
```
       error: hash mismatch in fixed-output derivation '/nix/store/fplwagni4m0msi0sx6mjvpiznhlhk98q-source.drv':
         specified: sha256-AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=
            got:    sha256-K3wCzwaGOsaiCm2LW4Oc4XOnp6agrdTxCxqEIMq0fuU=
```

### Additional context

See #1693 

`default.nix`/`shell.nix`/`flake.nix`:
```nix
```

`pyproject.toml`:
```toml
```

`poetry.lock`:
```toml
```

**Comment by heyzec** [comment]
This will probably be fixed by https://github.com/nix-community/poetry2nix/pull/1726
