### ISSUE TITLE
Failure to fetch private dependencies (legacy fetcher, wheels)

### ISSUE THREAD

**Issue by suntropez** [nix-community/poetry2nix#1740]
With https://github.com/nix-community/poetry2nix/pull/1734 `poetry2nix` started using `fetch-legacy.py` from `nixpkgs` (currently `/nix/store/wz9fz4vhxssffjrk07qvw3rj1jy0lgfg-fetch-legacy.py`). That script differs from the previous `fetch-legacy` in that if the URL has username/password the SSL context is set to check certificates.

If there is not authorization it skips it.

```
    else:  # If we are not using authentication disable TLS verification for long term reproducibility
       context.check_hostname = False
       context.verify_mode = ssl.CERT_NONE
```

However, the old script (currently `/nix/store/0rzh74dywg10ggl3ds6khsdpc84nbp96-fetch-from-legacy.py` here for me) disabled the verification always.

```
context = ssl.create_default_context()
context.check_hostname = False
context.verify_mode = ssl.CERT_NONE
```

This wouldn't be an issue, if not for `NIX_SSL_CERT_FILE` not being given to the wheel fetching derivation (`src` of the package), which results in 

```
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)>
```

If the derivation produced there is changed to pass in `NIX_SSL_CERT_FILE` then via `strace` we clearly see the diference between working and non-working:
```
1030393 openat(AT_FDCWD</home/...>, "/etc/ssl/certs/ca-certificates.crt", O_RDONLY) = 3</etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem>
```
(the latter part of that is that `ca-certificates.crt` symlinks to in my host)

Having `NIX_SSL_CERT_FILE` defined in the Nix daemon (and attested via `/environ` of the daemons) makes no difference.

I'm not sure what to blame here. I believe `nixpkgs` should be giving in that SSL path but I'm not sure of the implications outside of `--impure` (under which we are running our build, so it's not that). At the same time, it's a big change in `poetry2nix` behavior.

**Comment by declension** [comment]
Thanks for the investigation @suntropez! Found it _really_ hard to understand before seeing this ticket. 

FWIW I pinned poetry2nix at 46ce1e17d4a97a3cd5bf5433a7afd8d3e09ee106 and things seem OK with that.

**Comment by deliciouslytyped** [comment]
I got hung up on: `error: evaluation aborted with the following error message: 'Function called without required argument 
"fetchPypiLegacy" at /nix/store/5d0gzyfs6r6i18b9pc0x7ii0vcj2px2w-poetry2nix-src/mk-poetry-dep.nix:9'`

The solution appears to be to get a newer nixpkgs.

**Comment by slenderq** [comment]
Had the same issue today. Fixed it by using nixpkgs unstable in my flake.

**Comment by adisbladis** [comment]
I believe https://github.com/NixOS/nixpkgs/pull/333679 is the best solution.
We want the improved security from TLS when transferring credentials, but normally we don't.

**Comment by adisbladis** [comment]
Fixed in nixpkgs.
