### ISSUE TITLE
python.withPackages causes: unexpected argument 'self'

### ISSUE THREAD

**Issue by newkozlukov** [nix-community/poetry2nix#176]
Steps to reproduce:
---

1.
 ```nix
# shell.nix
with import <nixpkgs> {};
with pkgs;
with python38Packages;

let python = python38.withPackages (ps: [ps.pytorch]);
in poetry2nix.mkPoetryEnv {
    projectDir = ./.;
    python = python;
}
```

2. `nix-shell`

Expected:
---

1. A shell with python , current project and pytorch available

Observed:
---

```bash
~/n/poetry2nix-override (master)> nix-shell
error: anonymous function at /nix/store/afhj77bl1makqdxj3gsvcp6iv1s7m7zd-nixpkgs-21.03pre243353.6d4b93323e7/nixpkgs/pkgs/development/interpreters/python/wrapper.nix:1:1 called with unexpected argument 'self', at /nix/store/afhj77bl1makqdxj3gsvcp6iv1s7m7zd-nixpkgs-21.03pre243353.6d4b93323e7/nixpkgs/lib/customisation.nix:69:16
(use '--show-trace' to show detailed location information)
```

**Comment by adisbladis** [comment]
This is not supposed to work.
Calling `withPackages` results in a very different derivation from the unwrapped interpreter (`pkgs.python38`).

Why are you not adding `pytorch` to your `pyproject.toml`?
`poetry2nix` is not supposed to take packages from nixpkgs.

**Comment by newkozlukov** [comment]
@adisbladis Oh, allright then. But just so you know about the use case, I wanted my environment to reuse the already installed pytorch with a symlink, hoping that `poetry` then would then deduce that the dependency is already satisfied. The same way I would with `conda` environemtn. This allows to save a lot of storage when you have multiple projects referring to the same version of a package, which is non-neglegible in case of huge binary distributions like pytorch, numpy, opencv, etc.

Also, apparently I'm not the first to attempt to use `poetry2nix` with `python.withPackages`: https://nix-data.slack.com/archives/CSBATH2CX/p1588790947061300 (I do not know that person's use-case, though)
