### ISSUE TITLE
projectDir when not using local checkout but import ?

### ISSUE THREAD

**Issue by 573** [nix-community/poetry2nix#178]
I am using github as source to build an application.
How would I specify `projectDir` in that case ?

```
let
  # `git ls-remote https://github.com/nixos/nixpkgs-channels nixos-unstable`
  pkgs = import (builtins.fetchGit {
    name = "nixpkgs";
    url = "https://github.com/nixos/nixpkgs/";
    rev = "441a7da8080352881bb52f85e910d8855e83fc55";
    ref = "refs/heads/nixos-unstable";
  }) {};
  poetry2nix = import (builtins.fetchGit {
    url = "https://github.com/nix-community/poetry2nix";
    rev = "133d569d2ebc80366da980d0b9db439b2fb2192f";
    ref = "refs/heads/master";
  }) {};
in
with pkgs;
poetry2nix.mkPoetryApplication rec {
  inherit python;
  projectDir = ./.; <<< when using src = fetchFromGitHub something else is needed
  src = fetchFromGitHub {
      owner = "jrnl-org";
      repo = "jrnl";
      rev = "888981c11e86061b0c6b53f065c28d2716395beb";
      sha256 = "ab79213e5819addbe95b7a46b32eeade0e6ce286";
    };
  doCheck = false;
  doInstallCheck = false;
  dontUseSetuptoolsCheck = true;
  pythonImportsCheck = [ ];
}
```

**Comment by 573** [comment]
I am aware I could do things like

```
nix-repl> ((lib.attrsets.getOutput) "out" pkgs.fetchFromGitHub { owner = "jrnl-org"; repo = "jrnl"; rev = "888981c11e86061b0c6b53f065c28d2716395beb"; sha256 = "1mmwdfj6wqmc4p7pf00x28j64j21ixkkr16fcc4gqdwlpxwkpkai"; }).drvPath
"/nix/store/9m4751ji3y9nwwn7aks16ghhhvww8bk2-source.drv"
```

but that still isn't what I wanted. If I sneak into `vim /nix/store/9m4751ji3y9nwwn7aks16ghhhvww8bk2-source.drv` I can just grab the first entry as in `Derive([("out","/nix/store/5664bfs1x205zyg0716jvi0p4ckz30vz-source"...` and sneak into `ls /nix/store/5664bfs1x205zyg0716jvi0p4ckz30vz-source` which is exactly the path I need.

But how to do that more nixish ?

**Comment by adisbladis** [comment]
You could do this:
``` nix
poetry2nix.mkPoetryApplication rec {
  inherit python;
  projectDir = src;

  overrides = poetry2nix.overrides.withDefaults(self: super: {
    keyring = super.keyring.overridePythonAttrs(old: {
      postPatch = ''
        substituteInPlace setup.py --replace 'setuptools.setup()' 'setuptools.setup(version="${old.version}")'
      '';
      propagatedBuildInputs = old.propagatedBuildInputs ++ [ self.toml ];
    });
  });

  src = fetchFromGitHub {
      owner = "jrnl-org";
      repo = "jrnl";
      rev = "888981c11e86061b0c6b53f065c28d2716395beb";
      sha256 = "1mmwdfj6wqmc4p7pf00x28j64j21ixkkr16fcc4gqdwlpxwkpkai";
  };
  doCheck = false;
  doInstallCheck = false;
  dontUseSetuptoolsCheck = true;
  pythonImportsCheck = [ ];
}
```

`keyring` needed some additional patching, but `projectDir = src` works just fine, with the caveat that it's using IFD which may or may not matter for your use case.
If you want to include this package in nixpkgs you'll need to download `pyproject.toml`/`poetry.lock` as IFD is not allowed within nixpkgs.

**Comment by 573** [comment]
In line `poetryPkg = poetry.override { inherit python; };` nix-build says

>error: value is null while a set was expected, at /nix/store/0dd00a08c24v06c0b6w78c3xzcw11ms1-source/default.nix:43:19

with the expression above.

**Comment by 573** [comment]
Seems related to [50](https://github.com/nix-community/poetry2nix/issues/50)

**Comment by adisbladis** [comment]
In your expression you're probably using `python2` since it's the default `python` attribute. Did you try using `python3` instead? (or omitting `python`, which will make `poetry2nix` default to `python3`).

**Comment by 573** [comment]
Leaving out `inherit python;` or even `let python = pkgs.python3;` doesn't solve it.
I guess your gut feeling is correct here ?

**Comment by 573** [comment]
Also regarding your comment

>at least one of the packages are not *python2* compatible

do you rather mean *python3* here ?

**Comment by 573** [comment]
This builds
```nix
{ pkgs ? import <nixpkgs> {}}:
pkgs.poetry2nix.mkPoetryApplication rec {
  inherit (pkgs) python3;
  projectDir = src;
  src = pkgs.fetchFromGitHub {
      owner = "jrnl-org";
      repo = "jrnl";
      rev = "eaaa7bb0e10df4ffd2a189a723e0c687305cb47a";            #
      sha256 = "0izwi706z3cn1jz30i6dpkh28k0gp2nwinf4597b7isn05m5m373";
  };
  doCheck = false;
  doInstallCheck = false;
  dontUseSetuptoolsCheck = true;
  pythonImportsCheck = [ ];
}
```
