### ISSUE TITLE
How to configure or create a poetry command using the nix env

### ISSUE THREAD

**Issue by eikek** [nix-community/poetry2nix#1781]
I'm new to poetry2nix and just used it on a project of ours. It works very well, thank you for this tool! I can drop into a dev shell and have a "fully configured" python command.

Our project is driven by a Makefile that makes use of `poetry run …` to do lots of build tasks. I couldn't find a way to create a poetry command that uses the environment build by nix. I can add poetry but then have still to do the `poetry install` to fill the virtual environment created by poetry somewhere in my homedir. I was hoping to somehow have poetry use the environment that was created by nix. 

I tried adding the result from `mkPoetryEnv` as the python command to `poetry.ovrride { python3 = … }`, which didn't work (that makes sense, as it's not the `python3` expression from nixpkgs)

I then tried to instruct poetry to use the dev shells python command with `poetry use env (which python)`, but this (strangely?) added a different path to the created virtual-env config. So doing `poetry env use /nix/store/abc…python3-3.12.4-env/bin/python` added a different path to `~/.cache/pypoetry/virtualenv/project-env/pyvenv.cfg` - the one to the standard python3 executable it seems.

When I replace the corresponding paths to python in the virtualenvs config to the one of my dev shell env, it seems to be working fine.

How can I add a poetry command to the dev shell that is using the python env/command from the nix build?

**Comment by declension** [comment]
Are you able to _not_ use `poetry` directly? That's kinda the best way here IMO. You definitely want to steer clear of `poetry install` once you're in poetry2nix world, gets very confusing.

`poetry2nix` will [create executables for all your Poetry scripts](https://github.com/nix-community/poetry2nix?tab=readme-ov-file#quickstart-non-flake), so if you're running `poetry run foo` (via `make foo` perhaps) then plain `foo` is the equivalent from within the Nix Shell (assuming a bit about how your `mkPoetryEnv` etc are set up)

This can even be re-wrapped when _not_ in the shell, e.g. 
`poetry run foo.sh`, so for you `poetry run make foo` might even be an option...

**Comment by eikek** [comment]
Hi @declension thank you very much! So I didn't realize that I have the commands just without `poetry` available! I couldn't find it in the docs, and I'm not sure why but I also cannot find it following your link in the readme 🤔 

That helps a lot, I don't have to use the Makefile as is, it is just fine for me to selectively run the poetry scripts I have in my env.

I don't do `poetry install`, of course, but I now also have a little script to hack in the correct paths (i.e. taken from dev shell `which python`) into the config file. So then even `poetry run …` will work. But now I'll probably just use the scripts selectively. Thanks again!

**Comment by declension** [comment]
FWIW it was this fairly hard-to-notice section in the example:

> Finally, you can run your Python application from the new ./result symlinked folder:
> 
> ```
> # replace <script> with the name in the [tool.poetry.scripts] section of your pyproject.toml
> program = "${myPythonApp}/bin/<script>";
> ```

**Comment by eikek** [comment]
Ah! Thank you again! I'm not familiar with the python world and I didn't connect this example correctly to be a solution for my problem :). We don't have a `[tool.poetry.scripts]` section, but it works the same for `[tool.mypy]` for example. And indeed, there are lots of useful tools in the `bin/` folder of the environment.

I close this issue as I'm happy now :-) I think it would still be very convenient to have a `poetry` command "automagically" created/available when entering the nix env. It would be useful for projects that use poetry via nix and without.
