### ISSUE TITLE
deprecated pytest-runner?

### ISSUE THREAD

**Issue by takeda** [nix-community/poetry2nix#1814]
Looks like right now nixpkgs deprecated pytest-runner and is throwing an error if it is used. This breaks many overrides (in my case I believe it is the faker package).

Not sure if it can be just removed from the overrides or should be replaced with something else, here's the error:

```
       error: pytest-runner has been removed as it uses deprecated features of setuptools and is deprecated by upstream
```

**Comment by Smona** [comment]
Looks like the issue can be fixed (at least for tinycss2, with `preferWheels = true;`) by simply removing the pytest-runner build input:

```nix
# in overrides:
tinycss2 = prev.tinycss2.overridePythonAttrs (old: {
  # remove pytest-runner
  buildInputs = [ ];
});
```

**Comment by cpcloud** [comment]
cc @adisbladis Any idea what we should do here? This effectively blocks a nixpkgs upgrade for anyone using poetry2nix with any packages in a project's closure that have a transitive dependency on `pytest-runner`.

I'm not sure why this was made a failure upstream, since a ton of packages depend (unnecessarily) on `pytest-runner`.

**Comment by edelagnier** [comment]
I still have this error when trying to follow the tutorlal but I don't seems to use pytest-runner anywhere ? Any clue on how to handle it ?

**Comment by arianvp** [comment]
Running into this too. Maybe we can make a dummy package in `poetry2nix` itself?

**Comment by 9999years** [comment]
I'm not sure where the dependency comes from, either, because `rg pytest-runner poetry.lock` doesn't turn up any results.

**Comment by 9999years** [comment]
Oh, poetry2nix actually adds it explicitly to a bunch of projects, like Pylint here, even though Pylint hasn't depended on `pytest-runner` since 2020:

https://github.com/nix-community/poetry2nix/blob/3ee1b0afb07a1b77b8e5c8eae34ca747818e415d/overrides/default.nix#L2279-L2283

(Sidenote, it's very frustrating that these overrides are basically impossible for users to modify without forking `poetry2nix`.)

**Comment by adisbladis** [comment]
> I'm not sure why this was made a failure upstream, since a ton of packages depend (unnecessarily) on pytest-runner.

I think the last few in-tree uses were gone. Nixpkgs is way too aggressive in pruning old Python packages.
The fix here is to add an override re-packaging pytest-runner.

**Comment by takeda** [comment]
@adisbladis I'm wondering if it would be acceptable for people who experience this error modify local poetry2nix to see if it still builds without pytest-runner and if it does make PR?

It looks like many packages no longer depend on it as @9999years pointed out pylint hasn't used it since 2020.

We tend to submit PRs when build breaks, but generally won't even notice when a dependency was removed already.

**Comment by 9999years** [comment]
A couple issues with removing `pytest-runner`:

- This test still depends on `pytest-runner` via https://github.com/trinodb/trino-python-client:

https://github.com/nix-community/poetry2nix/blob/3ee1b0afb07a1b77b8e5c8eae34ca747818e415d/tests/tzlocal/pyproject.toml#L9

- Poetry from Nixpkgs refuses to update lockfiles for the tests with `git` dependencies:

```
$ poetry --version
Poetry (version 1.8.3)
$ cd tests/text-generation-webui
$ poetry lock -v
Skipping virtualenv creation, as specified in config file.
Updating dependencies
Resolving dependencies... (0.0s)

  PermissionError

  [Errno 13] Permission denied: '/nix/store/9pj4rzx5pbynkkxq1srzwjhywmcfxws3-python3-3.12.5/src'

  at /nix/store/9pj4rzx5pbynkkxq1srzwjhywmcfxws3-python3-3.12.5/lib/python3.12/pathlib.py:1311 in mkdir
      1307│         """
      1308│         Create a new directory at this given path.
      1309│         """
      1310│         try:
    → 1311│             os.mkdir(self, mode)
      1312│         except FileNotFoundError:
      1313│             if not parents or self.parent == self:
      1314│                 raise
      1315│             self.parent.mkdir(parents=True, exist_ok=True)
```

**Comment by kqvanity** [comment]
I'm by no means an expert in python packages building systems, but pytest-runner was only present in the requirements_dev.txt, yet called unconditionally in setup.py, so I simply removed it e.g.,

```nix
  prePatch = ''
    substituteInPlace setup.py --replace "['pytest-runner', ]" "[]"
  '';
```
