### ISSUE TITLE
I can't upgrade the setuptools package past version 69.5.1.post0

### ISSUE THREAD

**Issue by Kaddu720** [nix-community/poetry2nix#1851]
### Describe the issue
When I set setuptools in my pyproject.toml file to `setuptools = "^75.2.0"` and try to build my project with the `nix  build` command, I get the following error. 

` >   - setuptools<76.0.0,>=75.2.0 not satisfied by version 69.5.1.post0`

No matter what I've tried, my setuptools is always pinned to that version.

I ran the `nix flake update` and  `poetry update` commands to make sure there where no conflicting dependencies. Every other package in my project updated properly, but setuptools was held back.

Here is my pyproject.toml:
```
[tool.poetry.dependencies]
python = "^3.11"
<other packages>
poetry-core = "^1.9.1"
setuptools = "^75.2.0"

[build-system]
requires = ["poetry-core>=1.9.1"]
build-backend = "poetry.core.masonry.api"
```

Here is the packaged in my poetry.lock
```
[[package]]
name = "setuptools"
version = "75.2.0"
description = "Easily download, build, install, upgrade, and uninstall Python packages"
optional = false
python-versions = ">=3.8"
files = [
    {file = "setuptools-75.2.0-py3-none-any.whl", hash = "sha256:a7fcb66f68b4d9e8e66b42f9876150a3371558f98fa32222ffaa5bced76406f8"},
    {file = "setuptools-75.2.0.tar.gz", hash = "sha256:753bb6ebf1f465a1912e19ed1d41f403a79173a9acf66a42e7e6aec45c3c16ec"},
]
```

How can I stop setuptools from being pinned to 69.5.1.post0?

**Comment by wlcx** [comment]
Dup of #1729

**Comment by Kaddu720** [comment]
> Dup of #1729

I mean, that conversation didn't come to a conclusion about the problem. Do you know how to solve it?

**Comment by Kaddu720** [comment]
Solutions, I had to move from nixpkgs-24.05 to nixpkgs-unstable.
