### ISSUE TITLE
flake.nix: provide a template

### ISSUE THREAD

**Issue by FRidh** [nix-community/poetry2nix#191]
Be able to package an application with `poetry2nix` using e.g.
```
nix flake init -t github:nix-community/poetry2nix#application
```

Note a `flake.lock` should be added to this repository to ensure a fixed version of `poetry`is used. Also, without it `--no-write-lock-file` needs to be added.

Aside from the application template I imagine templates for the other options, or one template for them all, could work as well.

**Comment by adisbladis** [comment]
There is a template at https://github.com/nix-community/poetry2nix/blob/master/templates/app/flake.nix and more contributions are welcome through PRs.
