### ISSUE TITLE
unexpected argument 'editablePackageSources'

### ISSUE THREAD

**Issue by jerbaroo** [nix-community/poetry2nix#195]
Hi I'm pretty new to this package. I have adapted a previous `.nix` file that used `mkPoetryApplication` to use `mkPoetryEnv` but I seem to be doing something wrong. I am on NixOS 20.03. Any help is appreciated.

```
> nix-build
error: 'mkPoetryEnv' at /nix/store/g7zakq50cxydki7w62g0d5dfax0h5prb-nixos-20.03.3112.08d429920bc/nixos/pkgs/development/tools/poetry2nix/poetry2nix/default.nix:133:5 called with unexpected argument 'editablePackageSources', at /home/jeremy/bridge-sim/default.nix:3:1
```

default.nix
```
{ pkgs ? import <nixpkgs> {} }:

pkgs.poetry2nix.mkPoetryEnv {
  projectDir = ./.;
  python = pkgs.python38;
  editablePackageSources = {
    bridge-sim = ./bridge_sim;
  };
}
```

**Comment by teto** [comment]
probably you are on a too old version since on master, it exists https://github.com/nix-community/poetry2nix/blob/d460ed2be1d74fb0b267e881ff4c317d74479845/default.nix#L207

**Comment by adisbladis** [comment]
Most likely what @teto said.
