### ISSUE TITLE
tortoise-orm 0.16.17 (and probably other packages) recurse infinitely in presence of dependency cycles

### ISSUE THREAD

**Issue by K900** [nix-community/poetry2nix#196]
In particular, `tortoise-orm==0.16.17` requires `aerich`, which in turn requires `tortoise-orm`, causing infinite recursion. I'm not really familiar enough with Nix to tell if this is fixable :(

**Comment by adisbladis** [comment]
These are upstream packaging bugs and seems to have been resolved since.
I'm using them in https://github.com/tweag/trustix/blob/master/packages/trustix-nix-reprod/pyproject.toml.
