### ISSUE TITLE
Dependencies dependencies seem to be taken come from nixpkgs.

### ISSUE THREAD

**Issue by typetetris** [nix-community/poetry2nix#208]
If I read the code correctly, direct dependencies are either fetched via git used from local paths or fetched from pypi. But If I am not mislead, the dependencies dependencies need to come from nixpkgs, as mk-python-derivation from nixpkgs is used.

If that is correct, my hope "If poetry can build it, nix can build it from the expressions coming from poetry2nix." is wrong and that's ok, because there aren't any guaranties stated now. It would just be nice to advertise that in the README.

**Comment by typetetris** [comment]
At the moment I experience that in a project of mine. I can build the actual state just fine, but after calling poetry lock once again, it doesn't build any more because some package version was raised.

**Comment by adisbladis** [comment]
> If I read the code correctly, direct dependencies are either fetched via git used from local paths or fetched from pypi. But If I am not mislead, the dependencies dependencies need to come from nixpkgs, as mk-python-derivation from nixpkgs is used.

This is wrong, we only pick packages from nixpkgs as a last resort fallback.

> If that is correct, my hope "If poetry can build it, nix can build it from the expressions coming from poetry2nix." is wrong and that's ok, because there aren't any guaranties stated now. It would just be nice to advertise that in the README.

This is one of the goals of poetry2nix. Generally speaking, if a package build fails it's a "bug".

> At the moment I experience that in a project of mine. I can build the actual state just fine, but after calling poetry lock once again, it doesn't build any more because some package version was raised.

Is it possible for you to share your project or make a minimal repro?

**Comment by typetetris** [comment]
Not mine, but I think its the root cause for the build failure in my project. (I use nixops there.)

    https://github.com/NixOS/nixops.git

use sha 8de09879d7b1733bc4085257d5bf3cc734f1ed38

`nix-build` and `poetry build` work just fine, but when I do `poetry lock` and then `nix-build`, I get:

```
...
Processing /build/source
    Preparing wheel metadata ... done
Building wheels for collected packages: nixops
  Building wheel for nixops (PEP 517) ... done
  Created wheel for nixops: filename=nixops-2.0.0-py3-none-any.whl size=81711 sha256=267cf1650cfc89ea4b6cb75393de9010d880fe647918764920b385372df21a38
  Stored in directory: /build/pip-ephem-wheel-cache-g5r29kay/wheels/e1/fb/ff/3c7bf8327fe7b38e0848fbd084e404c8a61b776977c550714b
Successfully built nixops
Finished creating a wheel...
Finished executing pipBuildPhase
installing
Executing pipInstallPhase
/build/source/dist /build/source
Processing ./nixops-2.0.0-py3-none-any.whl
Requirement already satisfied: typing-extensions<4.0.0,>=3.7.4 in /nix/store/jd2783wcgkq6j5s2igypldjr2ysnsxxm-python3.8-typing-extensions-3.7.4.3/lib/python3.8/site-packages (from nixops==2.0.0) (3.7.4.3)
Requirement already satisfied: pluggy<0.14.0,>=0.13.1 in /nix/store/cxnhdbxxnh295sjkw97qf91i3zs4pp4d-python3.8-pluggy-0.13.1/lib/python3.8/site-packages (from nixops==2.0.0) (0.13.1)
Requirement already satisfied: PrettyTable<0.8.0,>=0.7.2 in /nix/store/jmpm6dbxgkgq99dz590l0hmpqykj1dvv-python3.8-prettytable-0.7.2/lib/python3.8/site-packages (from nixops==2.0.0) (0.7.2)
ERROR: Could not find a version that satisfies the requirement typeguard<3.0.0,>=2.7.1 (from nixops==2.0.0) (from versions: none)
ERROR: No matching distribution found for typeguard<3.0.0,>=2.7.1 (from nixops==2.0.0)
builder for '/nix/store/099y17751l2g0jgjnfw8w0am747567pv-python3.8-nixops-2.0.0.drv' failed with exit code 1
error: build of '/nix/store/099y17751l2g0jgjnfw8w0am747567pv-python3.8-nixops-2.0.0.drv' failed

```
`poetry` did come from `nixos-20.09`

```
Poetry version 1.0.10
```

**Comment by typetetris** [comment]
Diff in `poetry.lock` for `typeguard`:
```
 [[package]]
 category = "main"
 description = "Run-time type checker for Python"
 name = "typeguard"
 optional = false
 python-versions = ">=3.5.3"
-version = "2.9.1"
+version = "2.10.0"
```
and in the `[metadata.files]` section:
```
 typeguard = [
-    {file = "typeguard-2.9.1-py3-none-any.whl", hash = "sha256:e258567e62d28f9a51d4f7c71f491154e9ef0889286ad2f37e3e22e4f668b21b"},
-    {file = "typeguard-2.9.1.tar.gz", hash = "sha256:529ef3d88189cc457f4340388028412f71be8091c2c943465146d4170fb67288"},
+    {file = "typeguard-2.10.0-py3-none-any.whl", hash = "sha256:a75c6d86ac9d1faf85c5ae952de473e5d26824dda6d4394ff6bc676849cfb939"},
+    {file = "typeguard-2.10.0.tar.gz", hash = "sha256:d830132dcd544d3f8a2a842ea739eaa0d7c099fcebb9dcdf3802f4c9929d8191"},
 ]
```

**Comment by typetetris** [comment]
Would be a funny bug, if it was for the two digit minor version number.

**Comment by adisbladis** [comment]
Ok, I see where the confusion is coming from :)

That error is not really clear unless you know what to look for.
In this case `typeguard` attempts to use `setuptools-scm` to figure out the package version, but as we're not building from a git clone with `.git` available that data is missing, and hence the version bounds check fails.

I've added an override that works around this in 1894b501cf4431fb218c4939a9acdbf397ac1803.

**Comment by typetetris** [comment]
Confirmed it worked at: https://github.com/typetetris/nixops/commit/e40d66a893fae0ccbd9c255d7b4efa67e2c38b30
