### ISSUE TITLE
Munch needs pbr, override not working

### ISSUE THREAD

**Issue by timokau** [nix-community/poetry2nix#209]
I'm having problems installing munch. It [requires](https://github.com/Infinidat/munch/blob/develop/setup.py) PBR and the build fails because it is not in the automatically generated environment.

I tried to add it with an override, but that is not working. For some reason `poetry2nix` attempts to build two versions of `munch`, one of which seems to ignore my overlay:

```
these derivations will be built:
  /nix/store/c2ylzgqixmfrdb6wmsiaqvcvpvgplza8-python3.7-munch-2.5.0.drv
  /nix/store/g4vwzz0c0fk1bbnbdfxpm8mlf7br8nvp-python3.7-munch-2.5.0.drv
  /nix/store/q0lf191y3a5cc0j52rkkyqh0ln7gizq5-python3-3.7.9-env.drv
```

while the other builds fine. I'm using this override for testing:

```
      munch = super.munch.overridePythonAttrs (
        old: {
          buildInputs = old.buildInputs ++ [ self.pbr ];
          postPatch = ''
            substituteInPlace setup.py --replace "pbr>=3.0" "pbr"
            cat setup.py
            ${pkgs.ripgrep}/bin/rg pbr
          '';
        }
      );
```

The second `munch` build does not execute the `postPatch` phase, so apparently the overlay does not apply for it. I'm using [this](https://github.com/kiudee/cs-ranking) repo with an added `poetry add --dev sacred` (which then pulls in munch).

Any ideas why this is happening?

**Comment by adisbladis** [comment]
This seems to have been fixed somewhere along the way. Adding `sacred` to a test project works just fine now.
