### ISSUE TITLE
Add external dependencies in default.nix

### ISSUE THREAD

**Issue by ashkan-leo** [nix-community/poetry2nix#245]
Hello,

First, great project! Thank you for making this happen.

Is there a way to add external non-python dependencies to default.nix? I'm trying to add `mongodb` dependency to my python project and I have put it in the shell.nix file for now. I don't think this is the correct place for this since my project needs mongodb to run. 
Any help is appreciated.

**Comment by adisbladis** [comment]
This could be passed as a `buildInputs = [ pkgs.mongodb ];`, just as with any other derivation.
