### ISSUE TITLE
Something that looks like a missing Python dependency?

### ISSUE THREAD

**Issue by kirelagin** [nix-community/poetry2nix#257]
After failing with #256, I decided to try to use plain `jupyter` instead of `jupyterlab`, so I followed the same steps as outlined there except for the other package.

I got this:

```text
error: --- Error --- nix-daemon
builder for '/nix/store/pjv5cdkvh1r9jm2zn0x4w8bc8c540rfw-python3.8-jupyterlab-widgets-1.0.0.drv' failed with exit code 1; last 10 log lines:
       command: /nix/store/0yhk4sk4x9s9hsrf3p1skbfy1pwd1rbf-python3-3.8.5/bin/python3.8 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/build/pip-req-build-nvt85q5_/setup.py'"'"'; __file__='"'"'/build/pip-req-build-nvt85q5_/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /build/pip-pip-egg-info-6gqvuvbt
           cwd: /build/pip-req-build-nvt85q5_/
      Complete output (5 lines):
      Traceback (most recent call last):
        File "<string>", line 1, in <module>
        File "/build/pip-req-build-nvt85q5_/setup.py", line 6, in <module>
          from jupyter_packaging import (
      ModuleNotFoundError: No module named 'jupyter_packaging'
      ----------------------------------------
  ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

I find it rather hard to believe that Jupyter, a very popular package, can be broken in this way. However, adding `jupyter-packaging` as a dependency to `pyproject.toml` and then adding it to `buildInputs` of `jupyterlab-widgets` solved the problem.

What could be wrong here?

**Comment by adisbladis** [comment]
This is a case of https://github.com/python-poetry/poetry/issues/2789.

It is listed as a build-time dependency, and is not included in `poetry.lock`.

**Comment by l0b0** [comment]
@kirelagin After following your hints, adding `jupyter-packaging = "*"` to pyproject.toml and

```
jupyterlab-widgets = super.jupyterlab-widgets.overridePythonAttrs (old: {
  buildInputs = (old.buildInputs or [ ]) ++ [ self.jupyter-packaging ];
});
```

to the overrides I get this error:

> collision between `/nix/store/pspfiqdbgwd3ygay4sig6azdxn7wy0iw-python3.9-jupyter-core-4.9.1/lib/python3.9/site-packages/__pycache__/jupyter.cpython-39.pyc' and `/nix/store/147mbrhks6qxn9cb1n259wnbl2fwv9k5-python3.9-jupyter-1.0.0/lib/python3.9/site-packages/__pycache__/jupyter.cpython-39.pyc'

Did you have to work around this somehow?
