### ISSUE TITLE
Is there a functionality to checks when building an app like witho other nix packages

### ISSUE THREAD

**Issue by takeda** [nix-community/poetry2nix#263]
In traditional nix package, when they are built they often run unit tests. I'm wondering if poetry2nix allows similar functionality? I tried adding `doCheck = true;` but looks like this is just ignored.

**Comment by adisbladis** [comment]
Poetry doesn't track development dependencies of other packages, so this won't work for dependencies of your package.
It should work just fine for leaf packages (`mkPoetryApplication`).

**Comment by takeda** [comment]
Ah it indeed works, I forgot to set `checkPhase = "pytest";`

Thanks!
