### ISSUE TITLE
Enable "develop = true" option for local dependencies to be installed as editable packages

### ISSUE THREAD

**Issue by rskew** [nix-community/poetry2nix#265]
Currently, local dependencies are not installed as editable packages. The `develop = true` option should cause poetry2nix to install these packages as editablePackage.

An alternative would be to have packages with source dir specified in the `editablePackageSources` of the top-level derivation mask the nix store version. Currently, the version from the nix store is used, and not the local source specified wtih `editablePackageSources`.

**Comment by zupo** [comment]
Related: https://discourse.nixos.org/t/how-to-debug-python-dependencies-when-using-poetry2nix

**Comment by teto** [comment]
`nix develop` should install it in editable install (but doesn't). It's a pain due to poetry but maybe poetry2nix could work around that (at least partially, I ). Warning I see when entering nix develop:
```
Executing pipShellHook
ERROR: File "setup.py" not found. Directory cannot be installed in editable mode: /home/teto/nova/docker-gitops
(A "pyproject.toml" file was found, but editable mode currently requires a setup.py based build.)
WARNING: You are using pip version 20.2.4; however, version 21.1.1 is available.
You should consider upgrading via the '/nix/store/5kznrncnp9v828a7i723j72bh9wkbkg7-python3-3.8.8/bin/python3.8 -m pip install --upgrade pip' command.
Finished executing pipShellHook
```

**Comment by adisbladis** [comment]
See https://github.com/nix-community/poetry2nix/pull/487
