### ISSUE TITLE
Evaluation error with conditional dependencies and overrides

### ISSUE THREAD

**Issue by timokau** [nix-community/poetry2nix#272]
I see this issue with `pyzmq`, which [requires](https://github.com/zeromq/pyzmq/blob/6b2eff76274d4ed9521ad292ca097cf63b939049/setup.py#L1392) `cffi` when the interpreter is `pypy`. This results in

```
[[package]]
name = "cffi"
version = "1.14.5"
description = "Foreign Function Interface for Python calling C code."
category = "main"
optional = false
python-versions = "*"
marker = "implementation_name == \"pypy\""
```

in `poetry.lock`. When I try to use `poetry2nix` I get

```
error: value is null while a set was expected, at /nix/store/f07i16zy5xgkw5fh79is87ax76j43vp0-nixpkgs-7d804ec1692d96c3810710098849531d8ca81d4d/pkgs/development/tools/poetry2nix/poetry2nix/overrides.nix:104:7
```

which refers to the `super.cffi.overridePythonAttrs` part of this override:

```nix
cffi =
# cffi is bundled with pypy
if self.python.implementation == "pypy" then null else
(
  super.cffi.overridePythonAttrs (
    old: {
      buildInputs = (old.buildInputs or [ ]) ++ [ pkgs.libffi ];
    }
  )
);
```

I think (without being very familiar with the poetry2nix internals) that `super.cffi` is `null` since it is filtered out by the marker. For some reason it is evaluated anyway, which fails because of the override. In this case I can work around it by simply setting `cffi = null`, since it is not required by `pyzmq` for the cpython interpreter.

**Comment by adisbladis** [comment]
I need some more context (like your full `pyproject.toml`/`poetry.lock`).

**Comment by timokau** [comment]
This seems related to #50, but is not fixed by #52. Maybe that is related to the different type of constraint (`python_version` vs `implementation_name`).

I can prepare a reproducible example tomorrow.

**Comment by timokau** [comment]
This is more complicated than I had though. Running `poetry lock` generates a new lock file which does not have the marker for the `cffi` package anymore. It adds the marker to `package.dependencies` instead, which does not seem to cause the same issue:

```
[[package]]
name = "pyzmq"
version = "22.0.3"
description = "Python bindings for 0MQ"
category = "main"
optional = false
python-versions = ">=3.6"

[package.dependencies]
cffi = {version = "*", markers = "implementation_name == \"pypy\""}
py = {version = "*", markers = "implementation_name == \"pypy\""}
```

I'm not sure which poetry version I had in my environment when I originally generated the lock file. Maybe it wasn't the one that should have been associated with the `shell.nix` file. It could just have been a usage error on my side.

I will close this for now. I'll reopen if this continues to be a problem and if I can provide more information. For now sorry for the noise.

**Comment by adisbladis** [comment]
> I will close this for now. I'll reopen if this continues to be a problem and if I can provide more information. For now sorry for the noise.

Thank you for the report :) Hopefully this won't pop up again.
