### ISSUE TITLE
`overrides.withDefaults` for packages with a dot (.) in their name

### ISSUE THREAD

**Issue by eganjs** [nix-community/poetry2nix#275]
`ruamel.yaml` is a dependency in one of my poetry projects, I've been trying to use `mkPoetryEnv` with it, however I don't seem to be able to override the configuration for the package to fix issues.

I suspect the issue is to do with the dot (.) in the package name.

I've tried a few keys, but have made no progress:
```
...
overrides = poetry2nix.overrides.withDefaults {
  self: super:

  {
    ruamel-yaml = super.ruamel-yaml.overridePythonAttrs (
      old: {
        preferWheel = true;
      }
    );

    ruamel_yaml = super.ruamel_yaml.overridePythonAttrs (
      old: {
        preferWheel = true;
      }
    );

    ruamel.yaml = super.ruamel.yaml.overridePythonAttrs (
      old: {
        preferWheel = true;
      }
    );

    "ruamel.yaml" = super."ruamel.yaml".overridePythonAttrs (
      old: {
        preferWheel = true;
      }
    );
  }
};
...
```

**Comment by p-h** [comment]
Are you doing this to get around the

```
ERROR: Could not find a version that satisfies the requirement ruamel.yaml.clib>=0.1.2; platform_python_implementation == "CPython" and python_version < "3.10" (from ruamel.yaml==0.16.13) (from versions: none)
ERROR: No matching distribution found for ruamel.yaml.clib>=0.1.2; platform_python_implementation == "CPython" and python_version < "3.10" (from ruamel.yaml==0.16.13)
```

issue?

**Comment by eganjs** [comment]
I am and although that is the reason, I do think it is a separate problem to what I've raised this issue for.

That said, if you can offer advice about that, I would appreciate it.

**Comment by p-h** [comment]
I'm afraid not. I have no clue on how to fix or work around this.

**Comment by RaitoBezarius** [comment]
Just got bitten by this (and both issues).

**Comment by hugecannon** [comment]
This related issue solved my version of this problem, maybe it can help here?

https://github.com/nix-community/poetry2nix/issues/322#issuecomment-874944931

**Comment by adisbladis** [comment]
The correct canonicalisation according to `moduleName = name: lib.toLower (lib.replaceStrings [ "_" "." ] [ "-" "-" ] name)` is `ruamel-yaml`.
