### ISSUE TITLE
Add support for private package repository (like the one from Gitlab)

### ISSUE THREAD

**Issue by mickours** [nix-community/poetry2nix#277]
Poetry support [private package repository](https://python-poetry.org/docs/repositories/#install-dependencies-from-a-private-repository) using this configuration:
```toml
[[tool.poetry.source]]
name = "foo"
url = "https://foo.bar/simple/"
```

Also, [Gitlab provide a nice feature](https://docs.gitlab.com/ee/user/packages/pypi_repository/index.html#install-a-pypi-package) to host python packages repository for each project.

I've setup this with poetry and its working but poetry2nix seems to not support it for now because it only looks for my package in the Pypi mirror:
```
trying https://files.pythonhosted.org/packages/source/r/ryax-common/ryax-common-1.4.2.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404 
error: cannot download ryax-common-1.4.2.tar.gz from any mirror
```

I'd be glad to add this feature myself but I really don't know where to start. Any advice on where we can add private package repository? Maybe overriding the [fetchurl mirrors list](https://github.com/NixOS/nixpkgs/blob/master/pkgs/build-support/fetchurl/mirrors.nix#L413)?

**Comment by adisbladis** [comment]
Do you have an example of a public package stored on a different mirror? 
If I were to add this feature I'd need a test case.

**Comment by mickours** [comment]
Thanks for your interest in this!

 I've tried to work on this myself by implementing a custom `FetchFromPypi` function but it is more complicated then I expected:
First, all packages should be fetch from personal repository before and then fetch it from the official Pypi repo and if not available. To do so, It needs to:
- parse the repository HTML page to see if the package is present. 
- If it is, it need to parse the package HTML page and get the download URL from the filename. 
- Finally, it can be downloaded and the Hash can be checked.
- If anything fails, try with the next repository (and ultimately pypi.org)

Another concern is to enable private repository access like provided by Gitlab: 
`https://__token__:<your_personal_token>@gitlab.com/api/v4/projects/25574279/packages/pypi/simple`

Poetry requires to configure the credentials using the  `http-basic.<repository-name>` configuration. I'm unable to find where the auth credential are stored: there is an `~/.config/pypoetry/auth.toml` file but it only contains username and no passwords. Maybe we can get it from an extra parameter to the `mkPoetry*` functions?


For testing, here is an example package repository from Gitlab which is public:
https://gitlab.com/ryax-tech/public/logfmt-logger/-/packages/1494123

You can access the Pypi repository at:
https://gitlab.com/api/v4/projects/25574279/packages/pypi/simple

With poetry you must add this to your pyproject.toml file:
```yaml
[[tool.poetry.source]]
name = "gitlab"
url = "https://gitlab.com/api/v4/projects/25574279/packages/pypi/simple/"
```

And then add it to you test project with:
```sh
poetry add logfmt-logger
```

**Comment by nlewo** [comment]
FYI, with this [commit](https://github.com/nlewo/poetry2nix/commit/7e0d4354063b73ed21b3dc0311a2479d27e43dd1), I have been able to fetch packages from a private Devpi instance.
Basically, i implemented a custom fetcher that first queries the "API", parse the output to extract the URL used to actually download the package archive. 

I however don't know what to do with this yet:/ 
If pypi still exposes this legacy API, maybe you could write a `poetry.lock` file with `source.type=legacy` to force packages to be downloaded using this legacy API.

**Comment by mickours** [comment]
Did you test this with private repository which requires credentials like the one from Gitlab?

**Comment by nlewo** [comment]
No, i didn't try and i don't think credentials are currently supported.
@mickours If you have a access to a private repository, it would be nice if you could check and reopen this issue if it is still not working.

**Comment by rskew** [comment]
Hey folks, I've had a go at enabling credentials for legacy repos, draft PR here: https://github.com/nix-community/poetry2nix/pull/390
