### ISSUE TITLE
No longer works on 20.09 (setuptools-rust)

### ISSUE THREAD

**Issue by kirelagin** [nix-community/poetry2nix#279]
When trying to run anything with the current version of `poetry2nix` on NixOS 20.09, it fails with:

```text
error: attribute 'setuptools-rust' missing

       at /nix/store/amr6lvz0iwh1q6lx2qqa3h8d0986rmai-source/overrides.nix:140:66:

          139|       nativeBuildInputs = (old.nativeBuildInputs or [ ])
          140|         ++ lib.optional (lib.versionAtLeast old.version "3.4") [ self.setuptools-rust ]
             |                                                                  ^
          141|         ++ lib.optional (stdenv.buildPlatform != stdenv.hostPlatform) self.python.pythonForBuild.pkgs.cffi;
(use '--show-trace' to show detailed location information)
```

Indeed, `setuptools-rust` only exists in `unstable`. The use of `setuptools-rust` was introduced in 61f3dc5e5412eee969d76bc119e993a7289e978b, however, somewhat weirdly, by bisecting I found out that the commit that actually triggers the issue for me is 11d203e2806a9860b4cfd31f552d72a2bcd7c6b9.

Overall, I think it is a bit unfortunate that `unstable` is now required, maybe it would be possible to instead add `setuptools-rust` in overlay here, until it gets released in a stable NixOS version?

**Comment by tewfik-ghariani** [comment]
I confirm that this is a breaking change

```
$ nix-build -I nixpkgs=channel:nixos-20.09 -I poetry2nix=/home/repositories/nix-community/poetry2nix
error: attribute 'setuptools-rust' missing, at /home/repositories/nix-community/poetry2nix/overrides.nix:146:66
(use '--show-trace' to show detailed location information)
```


Can someone take a look please?
cc @adisbladis , @AmineChikhaoui

**Comment by tewfik-ghariani** [comment]
@AmineChikhaoui actually suggested to point to NixOS 21.05 now that it is officially released, and that fixed the poetry2nix build error!

**Comment by adisbladis** [comment]
Considering that the NixOS release in question is no longer supported I will close this.
