### ISSUE TITLE
Using poetry2nix with flake "hangs" with no output

### ISSUE THREAD

**Issue by wangkev** [nix-community/poetry2nix#298]
When I try to use `poetry2nix` with `nix flake`, the new experimental commands (e.g. `nix build`, `nix shell`, `nix develop`) seem to just hang. Worth noting that I am on an intel mac, although `nix flake` generally works fine. There is also no output displayed either. 

```
~/poetry2nix_flake $ nix build
<nothing output here>
```

Not sure how to debug/dig further. Repro [here](https://github.com/wangkev/poetry2nix_flake). Any help would be appreciated!

**Comment by adisbladis** [comment]
I think you're missing a source directory in your reproduction case, so it's not usable as-is.
Could you fix that so I could take a look?

**Comment by wangkev** [comment]
Just added a `src` directory to the project root. Is that what you mean?

**Comment by wangkev** [comment]
Reinstalled nix and that solved the issue here.
