### ISSUE TITLE
[guidance] is there a way to get list of all non-dev locked dependencies?

### ISSUE THREAD

**Issue by takeda** [nix-community/poetry2nix#302]
Is there a way to get list of all non-dev locked dependencies?

Basically I'm wondering if I can somehow get all dependencies that would be equivalent of generating `requirements.txt` with non-dev dependencies) then installing them into specified directory.

Just a little background. I'm using poetry2nix for a project that deploys as aws lambda. Everything works really well, but for deployment I'm using serverless framework (it's a nodejs application that packages the application and deploys it in AWS as lambda).

The serverless supports python apps and also can get use poetry to collect all dependencies. The problem is that it doesn't understand Nix, and re-downloads all the dependencies from PyPI. I was thinking about building its cache directory using Nix (and point it by `https://github.com/UnitedIncome/serverless-python-requirements#other-caching-options`) so I could reuse packages built by Nix. The `mkPoetryPackages` seems like it would be it, except it includes all packages, including dev ones and also looks like it only contains the immediate dependencies.

**Comment by adisbladis** [comment]
You could use a combination of parsing `pyproject.toml` file yourself & using `mkPoetryPackages` and picking any attr names from `python.pkgs.${attr}`.
