### ISSUE TITLE
Support for lockfile with metadata.hashes instead of matadata.files key

### ISSUE THREAD

**Issue by pasqui23** [nix-community/poetry2nix#31]
When I do `poetry lock` the resulting `poetry.lock` has a `[[metadata.hashes]]` instead of a `[[metadata.files]]` section,and `nix-build` fail on it.
The structure is also different,so I can't simply replace it manually.

**Comment by pasqui23** [comment]
Resolved by updating from the ancient v0.12 to the v1.0 in nixpkgs-unstable

**Comment by adisbladis** [comment]
This lock file change was made for poetry2nix, we can't work with the old format as it's not rich enough.
