### ISSUE TITLE
moto package depends on package that doesn't exist 

### ISSUE THREAD

**Issue by takeda** [nix-community/poetry2nix#315]
When trying to build `moto` it fails with following error:

```
Processing ./moto-1.3.16-py2.py3-none-any.whl
Requirement already satisfied: mock in /nix/store/ypnww534syvxm259ngvhyjzgn2skdqpm-python3.8-mock-4.0.3/lib/python3.8/site-packages (from moto==1.3.16) (4.0.3)
Requirement already satisfied: cfn-lint>=0.4.0 in /nix/store/fjlvk21rzr9mh46m693lp7wcazp10jag-python3.8-cfn-lint-0.48.1/lib/python3.8/site-packages (from moto==1.3.16) (0.48.1)
Requirement already satisfied: jsondiff>=1.1.2 in /nix/store/3y3mfnky7z6bxh4plnyai569y2vabx1s-python3.8-jsondiff-1.2.0/lib/python3.8/site-packages (from moto==1.3.16) (1.2.0)
Requirement already satisfied: aws-xray-sdk!=0.96,>=0.93 in /nix/store/4xvqbf8vpjg58gmn75kgl97pwvznr5im-python3.8-aws-xray-sdk-2.7.0/lib/python3.8/site-packages (from moto==1.3.16) (2.7.0)
Requirement already satisfied: cryptography>=2.3.0 in /nix/store/3sg8qr7mri0gnzj5zx76idcfijkq74wd-python3.8-cryptography-3.4.7/lib/python3.8/site-packages (from moto==1.3.16) (3.4.7)
Requirement already satisfied: botocore>=1.12.201 in /nix/store/q68s00m78yl3jws5d616bvci8fam1k22-python3.8-botocore-1.20.44/lib/python3.8/site-packages (from moto==1.3.16) (1.20.44)
ERROR: Could not find a version that satisfies the requirement sshpubkeys>=3.1.0; python_version > "3" (from moto==1.3.16) (from versions: none)
ERROR: No matching distribution found for sshpubkeys>=3.1.0; python_version > "3" (from moto==1.3.16)
builder for '/nix/store/zsgksmvv9ww2dcsz3skzscvb3f766zvv-python3.8-moto-1.3.16.drv' failed with exit code 1
cannot build derivation '/nix/store/aamsf5brsr8s4j87gsfwqba322k6s88d-python3-3.8.7-env.drv': 1 dependencies couldn't be built
```

It appears to depend on `sshpubkeys` package which is only needed when `ec2` extra is being installed: https://github.com/spulec/moto/blob/master/setup.py#L112

I traced this requirement to an override change that was updated with this PR:
https://github.com/nix-community/poetry2nix/commit/3484e377f9e0c4a469348b3f6571f4a6edbd896c#diff-9e070d83f19cc15366efc74d8828a77e0bea1c62e55afd83c8e19f17d907a7fdR582

I'm wondering why it was added to overrides is `poetry2nix` ignoring python extras?

**Comment by adisbladis** [comment]
Extras are embedded in the lock file, so provided you install `moto` with the extra in your poetry environment this should work.

I don't know exactly why this was added. @rskew?

**Comment by rskew** [comment]
This must have been a mistake that crept in while trying to add a collection of overrides that would make a particular project buildable via poetry2nix.

I've created a PR removing the problematic override: https://github.com/nix-community/poetry2nix/pull/494

Apologies for the problems this caused you @takeda
