### ISSUE TITLE
Can't install pendulum 2.1.2 on Linux

### ISSUE THREAD

**Issue by zupo** [nix-community/poetry2nix#324]
Installing latest pendulum 2.1.2 on Linux fails with `ERROR: pendulum-2.1.2-cp38-cp38-manylinux_2_32_x86_64.whl is not a supported wheel on this platform.`.

The workaround I am currently using is this:

```
  poetryOverrides = self: super: {
    pendulum = super.pendulum.override {
      preferWheel = true;
    };
  };
```

I've prepared a Minimal Reproducible Example that showcases the problem: https://github.com/niteoweb/big-sur-poetry-test/tree/pendulum

Surprisingly, building works fine on MacOS, maybe due to lack of sandboxing?

**Comment by NorfairKing** [comment]
I'm trying to upstream this workaround including a regression test, but I can't get the regression test to fail ..?

**Comment by adisbladis** [comment]
This is now fixed.

**Comment by zupo** [comment]
Confirmed it works in my example too, thanks!

https://github.com/niteoweb/big-sur-poetry-test/commit/e64e2e52476c0cdccee25f28d2cee52debb8b5d3
