### ISSUE TITLE
examples should include pkg-config override?

### ISSUE THREAD

**Issue by AlexMoutonNoble** [nix-community/poetry2nix#331]
Hi
Got an error trying the examples but adding:

`overrides = pkgs.poetry2nix.overrides.withDefaults (self: super: { pkg-config = pkgs.pkg-config; });`

Got me through. Should this override stand or is this an error itself?

**Comment by adisbladis** [comment]
I'm sorry, but I don't really understand what the issue is here?

**Comment by AlexMoutonNoble** [comment]
Cant repro this morning. sorry for the noise.
Nix errors feel like learning haskell again for the first time.
