### ISSUE TITLE
Error: Package requires a different Python

### ISSUE THREAD

**Issue by yaitskov** [nix-community/poetry2nix#347]
Hi,

poentry2nix cannot provide python version specified in toml file.
nix-build builds everything and at the very end the system detects oh gosh - I was using wrong python version!

> processing /private/tmp/nix-build-python3.8-nb-0.1.0.drv-0/source
>     Preparing wheel metadata ... done
> ERROR: Package 'nb' requires a different Python: 3.8.9 not in '>=3.9,<4.0'
> 

Toml snippte:
```
[tool.poetry]
name = "nb"
version = "0.1.0"
description = ""
authors = ["x <x@email.com>"]

[tool.poetry.dependencies]
python = "^3.9"
Send2Trash = "^1.8.0"
appnope = "^0.1.2"
jupyter = "^1.0.0"

```

default.nix
```
 { pkgs ? import <nixpkgs> {} }: 
poetry2nix.mkPoetryApplication {
  projectDir = ./.;
}
```
It is serious drawback because poetry is very picky about python version.

If python version selection is not possible then at least check it before 5 min build run.

**Comment by adisbladis** [comment]
We don't automatically pick a Python version based on the description in `pyproject.toml` but you can explicitly pass one in:
``` nix
 { pkgs ? import <nixpkgs> {} }: 
poetry2nix.mkPoetryApplication {
  projectDir = ./.;
  python = pkgs.python39;
}
```

**Comment by yaitskov** [comment]
I see, though in my opinion I would make python attribute explicitly required then. 
This change would save lot's of time on first run.
