### ISSUE TITLE
poetry.lock - No such file on using poetry package as dependency

### ISSUE THREAD

**Issue by yaitskov** [nix-community/poetry2nix#353]
Hi,

I have a nix project depending on httpstan library.
The library recently moved to poetry2nix and buildPythonPackage fails due setup.py is not found.

I need to integrate classic nix plus python env with a derivation defined in terms of poetry2nix.
My first draft fails as follows:

```
let
  pkgs = import <nixpkgs> {};

  httpstan = pkgs.poetry2nix.mkPoetryPackages rec {
    projectDir = pkgs.fetchFromGitHub {
      owner = "stan-dev";
      repo = "httpstan";
      rev = "4.5.0";
      sha256 = "082m3j95cndh5m7zbyssxcd28k0sjyafl7w1z2l0pxdyma4p66ar";
    };
  };

  newpkgs = import pkgs.path {
    overlays = [ (self: super: {
      python39 =
        let
          packageOverrides = python-self: python-super: {
            appnope = python-super.appnope.overridePythonAttrs(old: {
              buildInputs = httpstan.poetryPackages;
            });
          };
        in super.python39.override {
          inherit packageOverrides;
        };
    } ) ];
  };

in (newpkgs.python39.withPackages (p: with p; [ appnope ])).env
```

Instead of appnope could be any package. 
I was needed a package to express dependency.

> led from /nix/store/rcwij9vv31639a41q1ws9ys4fi0ppsqm-nixpkgs-src/pkgs/development/interpreters/python/wrapper.nix:20:13:                         
> while evaluating 'requiredPythonModules' at /nix/store/rcwij9vv31639a41q1ws9ys4fi0ppsqm-nixpkgs-src/pkgs/top-level/python-packages.nix:65:27, cal
> led from /nix/store/rcwij9vv31639a41q1ws9ys4fi0ppsqm-nixpkgs-src/pkgs/top-level/python-packages.nix:83:33:                                       
> while evaluating 'hasPythonModule' at /nix/store/rcwij9vv31639a41q1ws9ys4fi0ppsqm-nixpkgs-src/pkgs/top-level/python-packages.nix:62:21, called fr
> om undefined position:                                                                                                                           
> while evaluating 'getOutput' at /nix/store/rcwij9vv31639a41q1ws9ys4fi0ppsqm-nixpkgs-src/lib/attrsets.nix:486:23, called from undefined position: 
> while evaluating anonymous function at /nix/store/rcwij9vv31639a41q1ws9ys4fi0ppsqm-nixpkgs-src/pkgs/stdenv/generic/make-derivation.nix:166:17, ca
> lled from undefined position:                                                                                                                    
> while evaluating anonymous function at /nix/store/rcwij9vv31639a41q1ws9ys4fi0ppsqm-nixpkgs-src/pkgs/development/tools/poetry2nix/poetry2nix/defau
> lt.nix:46:15, called from undefined position:                                                                                              
> while evaluating the attribute 'pkgs.apispec' at /nix/store/rcwij9vv31639a41q1ws9ys4fi0ppsqm-nixpkgs-src/pkgs/development/interpreters/python/def
> ault.nix:102:9:                                                                                                                                  
> while evaluating 'callPackageWith' at /nix/store/rcwij9vv31639a41q1ws9ys4fi0ppsqm-nixpkgs-src/lib/customisation.nix:117:35, called from /nix/stor
> e/rcwij9vv31639a41q1ws9ys4fi0ppsqm-nixpkgs-src/pkgs/development/interpreters/python/default.nix:24:24:                                           
> while evaluating 'makeOverridable' at /nix/store/rcwij9vv31639a41q1ws9ys4fi0ppsqm-nixpkgs-src/lib/customisation.nix:67:24, called from /nix/store
> /rcwij9vv31639a41q1ws9ys4fi0ppsqm-nixpkgs-src/lib/customisation.nix:121:8:                                                                       
> while evaluating anonymous function at /nix/store/rcwij9vv31639a41q1ws9ys4fi0ppsqm-nixpkgs-src/pkgs/development/interpreters/python/default.nix:2
> 5:10, called from /nix/store/rcwij9vv31639a41q1ws9ys4fi0ppsqm-nixpkgs-src/lib/customisation.nix:69:16:                                           
> while evaluating 'makeScopeWithSplicing' at /nix/store/rcwij9vv31639a41q1ws9ys4fi0ppsqm-nixpkgs-src/lib/customisation.nix:222:80, called from /ni
> x/store/rcwij9vv31639a41q1ws9ys4fi0ppsqm-nixpkgs-src/pkgs/development/interpreters/python/default.nix:77:12:                                     
> while evaluating 'extends' at /nix/store/rcwij9vv31639a41q1ws9ys4fi0ppsqm-nixpkgs-src/lib/fixed-points.nix:69:24, called from /nix/store/rcwij9vv
> 31639a41q1ws9ys4fi0ppsqm-nixpkgs-src/lib/customisation.nix:233:14:                                                                               
> while evaluating 'composeExtensions' at /nix/store/rcwij9vv31639a41q1ws9ys4fi0ppsqm-nixpkgs-src/lib/fixed-points.nix:75:17, called from /nix/stor
> e/rcwij9vv31639a41q1ws9ys4fi0ppsqm-nixpkgs-src/lib/fixed-points.nix:69:67:                                                                 
> while evaluating 'composeExtensions' at /nix/store/rcwij9vv31639a41q1ws9ys4fi0ppsqm-nixpkgs-src/lib/fixed-points.nix:75:17, called from /nix/stor
> e/rcwij9vv31639a41q1ws9ys4fi0ppsqm-nixpkgs-src/lib/fixed-points.nix:78:22:                                                                 
> while evaluating 'composeExtensions' at /nix/store/rcwij9vv31639a41q1ws9ys4fi0ppsqm-nixpkgs-src/lib/fixed-points.nix:75:17, called from /nix/stor
> e/rcwij9vv31639a41q1ws9ys4fi0ppsqm-nixpkgs-src/lib/fixed-points.nix:76:22:                                                                 
> while evaluating 'composeExtensions' at /nix/store/rcwij9vv31639a41q1ws9ys4fi0ppsqm-nixpkgs-src/lib/fixed-points.nix:75:17, called from /nix/stor
> e/rcwij9vv31639a41q1ws9ys4fi0ppsqm-nixpkgs-src/lib/fixed-points.nix:78:22:                                                                 
> while evaluating anonymous function at /nix/store/rcwij9vv31639a41q1ws9ys4fi0ppsqm-nixpkgs-src/pkgs/development/tools/poetry2nix/poetry2nix/defau
> lt.nix:221:20, called from /nix/store/rcwij9vv31639a41q1ws9ys4fi0ppsqm-nixpkgs-src/lib/fixed-points.nix:76:22:                             
> while evaluating 'readTOML' at /nix/store/rcwij9vv31639a41q1ws9ys4fi0ppsqm-nixpkgs-src/pkgs/development/tools/poetry2nix/poetry2nix/lib.nix:70:14
> , called from /nix/store/rcwij9vv31639a41q1ws9ys4fi0ppsqm-nixpkgs-src/pkgs/development/tools/poetry2nix/poetry2nix/default.nix:141:20:      
> opening file '/nix/store/9s0s802hiir0pgq47absr2ycpn8zh77c-source/poetry.lock': No such file or directory

**Comment by adisbladis** [comment]
This seems to be based on a series of misunderstandings..

- Installing a single library with poetry2nix doesn't make sense. It's a tool to manage entire Python environments.
- You are trying to mix 2 distinct python package sets, this is not supported by either nixpkgs or poetry2nix.

What are you actually trying to accomplish with this?

**Comment by yaitskov** [comment]
@adisbladis, 

> - Installing a single library with poetry2nix doesn't make sense. It's a tool to manage entire Python environments.

It does have a sense. Let me explain a trap my project end up. There is a nix repo for configuring Python env and it is used by dozen of projects. I don't even know all of them, but for sure all these projects are used by data scientists and need `stan`-like stuff. I don't have access to all of them. The repo is build with classic Nix approach in mind (i.e. buildPythonPackage).

pystan library was using `setup.py` but newer version switched to poetry2nix.

What options do I have? 
- Rewrite a heck of projects at once on poetry
- Fork pystan and continue support setup.py

None of them looks appealing to me.
I think I am not alone in such problem.

Looks this inflexibility hampers poetry2nix in gaining popularity and there for hampers poetry too, which is very young. Incremental migration would help a lot here.

For nix abstraction view an application developer I don't understand why it is not possible to mix both poetry into legacy project. My project doesn't have lock file, why not generate fake lock file?

**Comment by adisbladis** [comment]
> Looks this inflexibility hampers poetry2nix in gaining popularity and there for hampers poetry too, which is very young. Incremental migration would help a lot here.

Again, you have some fundamental misunderstandings about the interaction of the various components of this setup.

Poetry2nix is a tool to manage the _entire_ package build or environment for a _leaf package_ or _environment_.

You could still use the traditional `buildPythonPackage` method to package libraries depending on Poetry, such as in https://github.com/NixOS/nixpkgs/blob/04697264a425c1ea27b463fd660c95259b76f4a6/pkgs/development/python-modules/backoff/default.nix#L16 to just give you an example.
This is true for any Python build system such as `flit` too. These are not viral build systems.

**Comment by adisbladis** [comment]
You could use Poetry/Poetry2nix to manage your custom Python package set as such:

- `default.nix`
``` nix
let
  pkgs = import <nixpkgs> { };

  python = (pkgs.poetry2nix.mkPoetryPackages {
    projectDir = ./.;
    python = pkgs.python39;
  }).python;

in (python.withPackages (p: with p; [ appnope ])).env
```

- `pyproject.toml`
``` toml
[tool.poetry]
name = "poetry2nix-managed-env"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.9"
httpstan = "^4.5.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
```
