### ISSUE TITLE
Virtualenv fails to build on current nixpkgs master

### ISSUE THREAD

**Issue by ilikeavocadoes** [nix-community/poetry2nix#357]
The build of virtualenv fails with the following message:
```
ERROR: Could not find a version that satisfies the requirement backports.entry-points-selectable>=1.0.4 (from virtualenv==20.7.2) (from versions: none)
ERROR: No matching distribution found for backports.entry-points-selectable>=1.0.4 (from virtualenv==20.7.2)
```
Here's a tarball containing minimal pyproject.toml, poetry.lock, and shell.nix files to reproduce the issue: [minimal-example.tar.gz](https://github.com/nix-community/poetry2nix/files/7006005/minimal-example.tar.gz)

**Comment by adisbladis** [comment]
Fixed here https://github.com/nix-community/poetry2nix/commit/bcc679d1aeb4ee124d42d29ede7fe62f8a8d854c#diff-9e070d83f19cc15366efc74d8828a77e0bea1c62e55afd83c8e19f17d907a7fdR83-R90
