### ISSUE TITLE
Poetry2nix not using wheels even with `preferWheels = true`

### ISSUE THREAD

**Issue by tfmoraes** [nix-community/poetry2nix#362]
I create this github repository to show this problem: https://github.com/tfmoraes/poetry2nix_test

In this repository I used Niv to lock the Nixpkgs version (last in nixos-unstable) and Poetry2nix (also the last version). The project in this repository has two dependencies: numpy and cython. It uses `poetry2nix.mkPoetryEnv` to create a python environment with those two packages installed. I set it use wheels (`preferWheels = true`). But it's not using the wheels.

**Comment by tijolao** [comment]
this is happening to me too.

**Comment by imincik** [comment]
I confirm this issue as well. I am trying to avoid building numpy from source using following code, but it doesn't work

```
pkgs.poetry2nix.mkPoetryApplication {
    python = pkgs.python38;
    projectDir = builtins.path { path = ./.; name = "xyz"; };
    src = ./.;
    doCheck = false;
    overrides = 
        pkgs.poetry2nix.overrides.withDefaults (self: super: {

            # Use Python wheel to avoid lengthy compilation from source code
            numpy = super.numpy.override {
                preferWheel = true;
            };

        });
```

**Comment by imincik** [comment]
@adisbladis , I just found that [test_preferwheel.py](https://github.com/nix-community/poetry2nix/blob/master/tests/prefer-wheel/test_preferwheel.py) is empty file.

**Comment by imincik** [comment]
But setting global `preferWheels = true` works !

Example:

```
pkgs.poetry2nix.mkPoetryApplication {
    python = pkgs.python38;
    projectDir = builtins.path { path = ./.; name = "xyz"; };
    src = ./.;
    doCheck = false;
    preferWheels = true;  
```

**Comment by tfmoraes** [comment]
I tested here and `preferWheels` is working now.
