### ISSUE TITLE
`markers = "python_version < \"3.10\""` treated like 3.1?

### ISSUE THREAD

**Issue by l0b0** [nix-community/poetry2nix#379]
It looks like `markers = "python_version < \"3.10\""` is compared to the current Python version numerically, because removing it, for example from `importlib-metadata = {version = ">=3.6.0", markers = "python_version < \"3.10\""}`, turns a

> Could not find a version that satisfies the requirement importlib-metadata>=3.6.0; python_version < "3.10" (from pytest-randomly==3.10.1) (from versions: none)

error into no error. Another workaround is to change the marker into `"python_version < \"3.9.9999\"`.

Removing the marker from setup.cfg does _not_ help:

```nix
pytest-randomly = super.pytest-randomly.overrideAttrs (old: {
  postPatch = ''
    sed -i 's/importlib-metadata >= 3.6.0 ; python_version < "3.10"/importlib-metadata >= 3.6.0/' setup.cfg
  '';
});
```

Presumably because the poetry.lock restriction is also taken into account when trying to resolve a version.

This may be the underlying cause of https://github.com/nix-community/poetry2nix/issues/376.

In the meantime, is it possible to override the contents of poetry.lock? I don't see any other overrides doing that.

**Comment by cpcloud** [comment]
It's not actually being treated like `3.1`, rather the version comparison is executed as `"3.9" < "3.10"` which is false.
