### ISSUE TITLE
How to write a flake with a `devShell`

### ISSUE THREAD

**Issue by charmoniumQ** [nix-community/poetry2nix#384]
I'm starting with the nix flake template

```
nix flake init --template github:nix-community/poetry2nix
```
and then applying a patch like this:
```
@@ -15,6 +15,9 @@
           myapp = prev.poetry2nix.mkPoetryApplication {
             projectDir = ./.;
           };
+          myenv = prev.poetry2nix.mkPoetryEnv {
+            projectDir = ./.;
+          };
@@ -29,6 +32,7 @@
+        devShell = pkgs.myenv;
         defaultApp = apps.myapp;
       }));
 }
```

[Here](https://pastebin.com/EuG5Uh2K) is a minimal (not) working example. However, `nix develop --command python -c "import sly"` says `ModuleNotFound`, despite `sly` residing in `pyproject.toml` and `poetry.lock`.

**Comment by charmoniumQ** [comment]
Ope, I got it working.

```
@@ -15,6 +15,9 @@
           myapp = prev.poetry2nix.mkPoetryApplication {
             projectDir = ./.;
           };
+          myenv = prev.poetry2nix.mkPoetryEnv {
+            projectDir = ./.;
+          };
@@ -29,6 +32,7 @@
+         devShell = pkgs.mkShell {
+           buildInputs = [ myenv ];
+         };
         defaultApp = apps.myapp;
       }));
 }
```

**Comment by edrex** [comment]
For discoverability:
- https://github.com/NixOS/templates/blob/master/python/flake.nix has a devShell, although it only contains `pkgs.poetry`
- I'm working on a template `github:edrex/flake-templates#python` ([src](https://github.com/edrex/flake-templates/blob/main/python/flake.nix) where `nix develop` drops you into a poetry env. It also has updates to work with Nix 2.7 (`defaultDevShell` -> `devShells.default`). I'll submit a PR to NixOS/templates after a bit more testing.
