### ISSUE TITLE
Using editablePackageSources with flakes

### ISSUE THREAD

**Issue by yrd** [nix-community/poetry2nix#425]
When using poetry2nix in a flake-based project, `editablePackageSources` doesn't seem to work as documented:

```nix
pkgs.poetry2nix.mkPoetryEnv {
  projectDir = ./.;
  python = pkgs.python39;
  editablePackageSources = {
    myProject = ./.;
  };
}
```

In this case, the `./.` always references the flake's source that was copied into the store (something like `/nix/store/p68s64y2g86wb02rj0am4q4wp4cj8mgs-source`). I found a workaround by doing something like this:

```nix
editablePackageSources = {
  myProject = builtins.getEnv "PWD";
}
```

This seems to work when running with `--impure`, but is there a better way to do this without relying on the environment variable?

**Comment by hhoeflin** [comment]
I guess fundamentally an editable package will never work with a pure flake, as the whole concept of pureness means it is not editable.

Your pointer helped me. One note, the "PWD" only works when the shell is invoked from the root of the project, so this is a bit of a tripwire. The alternative is to hardcode the path in your home folder into the flake ... also not nice but works as well, so for example

```
myporject = "${builtins.getEnv "HOME"}/projects/myproject";
```

**Comment by hhoeflin** [comment]
I agree that this may not be something that can be fixed in poetry2nix but as flakes are supposedly the new standard, some documentation on the README pointing out this issue would be helpful.

**Comment by adisbladis** [comment]
Flakes are not the new standard, they are an experimental feature.

**Comment by hhoeflin** [comment]
sorry, sure - it is an experimental feature. I am new to this, so I try to use it almost exclusively. As the flakes are mentioned on the README, I thought it would be good to at least point to some pitfalls. I certainly spent quite a bit of time with this issue as things didn't work as I hoped.

**Comment by hhoeflin** [comment]
Wanted to add my current workaround as  a solution. 

```nix
pkgs.poetry2nix.mkPoetryEnv {
  projectDir = ./.;
  python = pkgs.python39;
  editablePackageSources = {
    myProject = if builtins.getEnv "PROJECT_DIR" == "" then ./. else builtins.getEnv "PROJECT_DIR";
  };
}
```
This way, if the flake is pure, the flake directory is used and copied to the store (being reproducible as flakes intended). If `--impure`, then it uses the variable `PROJECT_DIR` if present. nix doesn't pass information as to where on the file system the flake is (and it may be on github etc anyway). But we can work around it, as bash gives this information when invoked. So write a short bash-script named e.g. `activate_env.sh`:

```bash
export PROJECT_DIR=$(dirname "$(realpath -s "${BASH_SOURCE[0]}")")
nix shell --impure $PROJECT_DIR
```
When sourced, it will drop you into the shell environment with editable sources.

**Comment by yrd** [comment]
@hhoeflin Thanks! I think that's a nice solution which causes less friction than only `PWD` while still using flakes (which, yeah, aren't pure anymore but I guess an in-development environment will never be so I think that's okay).
