### ISSUE TITLE
How to make sure environment is rebuilt on poetry.lock changes?

### ISSUE THREAD

**Issue by l0b0** [nix-community/poetry2nix#436]
[My Poetry Nix shell](https://github.com/linz/geostore/blob/159e842bb7be157a1009fc755cee182c351f2643/shell.nix) code basically looks like this:

```nix
let
  pkgs = import
    (
      fetchTarball {
        name = "21.05";
        url = "https://github.com/NixOS/nixpkgs/archive/7e9b0dff974c89e070da1ad85713ff3c20b0ca97.tar.gz";
        sha256 = "1ckzhh24mgz6jd1xhfgx0i9mijk6xjqxwsshnvq789xsavrmsc36";
      })
    { };
  poetryEnv = pkgs.poetry2nix.mkPoetryEnv {
    python = pkgs.python38;
    projectDir = builtins.path { path = ./.; name = "project-name"; };
  };
in
pkgs.mkShell {
  buildInputs = [
    poetryEnv
  ];
}
```

I also have a .envrc with `use_nix`.

I'd like to make sure it gets rebuilt every time poetry.lock is changed, to make sure I always have the latest package versions locally. How would I do that? As far as I know it means the finished package needs to have a reference to the actual files which should trigger a rebuild. One idea would be to `mkPoetryApplication` in default.nix and then use something like the following in shell.nix:

```nix
  poetryApp = import ./default.nix;
  poetryEnv = pkgs.poetry2nix.mkPoetryEnv {
    inherit (poetryApp) overrides projectDir python;
  };
```

, but `mkPoetryApplication` doesn't seem to expose all those properties.

**Comment by cpcloud** [comment]
Does `direnv`'s `watch_file` work for this?

**Comment by l0b0** [comment]
That'll probably do it, thanks!
