### ISSUE TITLE
Support for wheels using PEP 600 manylinux platform tags

### ISSUE THREAD

**Issue by gmacon** [nix-community/poetry2nix#449]
I've noticed that the `manylinux1`, `manylinux2010`, and `manylinux2014` platform tags are the only ones supported here. A new style of tag, defined in [PEP 600](https://www.python.org/dev/peps/pep-0600/) now exists using the pattern `manylinux_${GLIBCMAJOR}_${GLIBCMINOR}_${ARCH}`. PEP 600 also redefines all of the existing tags as aliases of tags in the new style.

I think this was the root cause of #306.

I think it would be good to support this new style of tag, though I don't have an immediate suggestion as to how that would best be done.

**Comment by SemMulder** [comment]
I can confirm this: [`open3d`](https://pypi.org/project/open3d/) is another library that fails to install because of this.
