### ISSUE TITLE
Documentation: equivalent of poetry install --no-dev

### ISSUE THREAD

**Issue by max-arrival** [nix-community/poetry2nix#47]
Hi!

I wonder if there's a standard way to ignore dev-dependencies when installing packages with `poetry2nix`?

**Comment by adisbladis** [comment]
You can skip installing dev-dependencies by setting `doCheck = false`.

`dev-dependencies` are only added as `checkInputs`.

**Comment by max-arrival** [comment]
awesome, thanks!
