### ISSUE TITLE
zipp-2.2.0 is broken

### ISSUE THREAD

**Issue by vlaci** [nix-community/poetry2nix#48]
Breakage is introduced by https://github.com/jaraco/zipp/commit/29c497286e9f8e835c68b7b4ddb9ff3635a273dc

`setup.py` wants to download `setuptools_scm[toml]` from the internet therefor it fails toinstall. I do not know enough of the internals of poetry2nix to suggest a proper fix. I see that `setuptools_scm` is a special case to prevent recursion errors. Is the `toml` extra always implied?

Removing the `toml` extras definition in an override fixed the issue for me, however I am not aware what side effect it has.

**Comment by robertodr** [comment]
Might this (and following comments) work for you? https://github.com/nix-community/poetry2nix/issues/41#issuecomment-579421339

**Comment by vlaci** [comment]
I think it may. Unfortunately I am only transitively depend on on `setuptools_scm`

**Comment by vlaci** [comment]
It indeed fixes the issue. I don't really like that it need needs to be referenced in `pyproject.toml` though.
