### ISSUE TITLE
Ability to add doCheck = false globally

### ISSUE THREAD

**Issue by vincentbernat** [nix-community/poetry2nix#485]
### Describe the issue
To speedup updates, it would be interesting to be able to not run tests when building all the Python packages. Some packages take quite a long time, for example, pytest has many tests and I am not interested to run them. I would be neat to achieve this without adding overrides for each packages.

**Comment by adisbladis** [comment]
`doCheck` _is_ `false` by default, but only if the package is created by `poetry2nix` which isn't always the case with e.g. pytest.

**Comment by vincentbernat** [comment]
You mean here? https://github.com/nix-community/poetry2nix/blob/f78937eed14e0518ce10416156045d45c9d5bdaa/mk-poetry-dep.nix#L113

I have tests running for pytest, but also for uvloop. When you say they are not created by `poetry2nix`, you mean they are built because something outside of `mkPoetryPackages` would require them?

Is `doCheck = false` enough? What about `dontUsePytestCheck = false` or `dontUseSetuptoolsCheck = true`? Are they covered by `doCheck = false`?

**Comment by adisbladis** [comment]
> I have tests running for pytest, but also for uvloop. 

Sometimes when an upstream dependency graph is incomplete and we add dependencies via overrides these are picked up from nixpkgs where tests _are_ enabled.
We do not have a good way to disable tests for those packages.

> Is `doCheck = false` enough?

It should be, with the caveat with packages picked up from the nixpkgs definitions.

**Comment by vincentbernat** [comment]
OK, understood. So, no issue in poetry2nix. I'll investigate a bit why packages took from nixpkgs are not pulled from the binary cache.

**Comment by adisbladis** [comment]
>  I'll investigate a bit why packages took from nixpkgs are not pulled from the binary cache.

This one is quite simple actually:
While we use the nixpkgs _definitions_ we overlay the Poetry-managed packages on top of the nixpkgs python set.
This means that any inputs to for example uvloop that are managed in your `pyproject.toml` & `poetry.lock` will be taken from the generated set and will have a different hash.

**Comment by vincentbernat** [comment]
Humm, another question. In https://github.com/nix-community/poetry2nix/blob/master/overrides.nix#L443, `doCheck` is set specifically to false. But not for `grpcio` a few lines later. Does this mean that when overrides are used, `doCheck` is true by default?

**Comment by adisbladis** [comment]
>  Does this mean that when overrides are used, doCheck is true by default?

No, I think setting `doCheck = false;` in that case is redundant.
