### ISSUE TITLE
Python version bounds for `pyproject.toml` are ignored -> Building poetry with Python 3.8 fails

### ISSUE THREAD

**Issue by Infinisil** [nix-community/poetry2nix#50]
Trying to build poetry with Python 3.8 fails:
```
$ nix-build -E 'with import <nixpkgs> {}; poetry.override { python = python38; }' -I nixpkgs=channel:nixpkgs-unstable
error: value is null while a set was expected, at /nix/store/24kjp6k6piq42jxvzx80imdx0ysz6grz-nixexprs.tar.xz
  /pkgs/development/tools/poetry2nix/poetry2nix/overrides.nix:569:27 (use '--show-trace' to show detailed location information)
```

This fails at https://github.com/nix-community/poetry2nix/blob/cdb1bd83a31d7ae12dd5b5b1ea460c11c942be16/overrides.nix#L569

because `super.zipp` is `null`. This is because `zipp` has a marker only indicating support for `< 3.8`: https://github.com/nix-community/poetry2nix/blob/cdb1bd83a31d7ae12dd5b5b1ea460c11c942be16/pkgs/poetry/poetry.lock#L1345-L1346

But the real problem is that `zipp` is evaluated at all, because `importlib-metadata`, the only package that depends on `zipp`, should only be a dependency for python < 3.8: https://github.com/nix-community/poetry2nix/blob/cdb1bd83a31d7ae12dd5b5b1ea460c11c942be16/pkgs/poetry/pyproject.toml#L58

And that condition is ignored because poetry2nix only parses package names, not their values: https://github.com/nix-community/poetry2nix/blob/cdb1bd83a31d7ae12dd5b5b1ea460c11c942be16/default.nix#L166-L170

I believe that's the correct diagnosis for this failure, and I think the solution is to parse these version constraints to conditionally include dependencies based on python version.

Digging through poetry's source code I found these methods for handling these version constraints: [`convert_dependencies`](https://github.com/python-poetry/poetry/blob/96191ca4f7551243366bda030426995fce5c4b57/poetry/masonry/builders/sdist.py#L272-L327) and [`to_pep_508`](https://github.com/python-poetry/poetry/blob/96191ca4f7551243366bda030426995fce5c4b57/poetry/packages/dependency.py#L201-L240). I think these might need to be implemented in Nix, which might be pretty easy with PEP 508 already implemented.

**Comment by adisbladis** [comment]
Fixed in #52
