### ISSUE TITLE
Question: How can one use the passthru in the overrides?

### ISSUE THREAD

**Issue by vale981** [nix-community/poetry2nix#514]
I recently fixed a typo that I came across while trying to get the `passthru` argument to work:
https://github.com/nix-community/poetry2nix/pull/509/commits/390173bce21aa5eaa65ea7171d75a75382e964f5

Unfortunately, I still could not find out how that could be achieved.
Specifying 
```nix
matplotlib = super.matplotlib.overridePythonAttrs (
                      old: {
                        passthru.enableTk = true;
                      }
                    );
```
in the overrides didn't seem to do anything.

**Comment by adisbladis** [comment]
This isn't at all obvious, but `passthru.args` is set to whatever is passed to the function that creates the derivation. 

Matplotlib didn't look at `passthru.args`, but instead looked at `passthru`.
This should be fixed in https://github.com/nix-community/poetry2nix/pull/516.

With this change you should be able to create an override looking something like:
```
matplotlib = super.matplotlib.override { enableTk = true; }
```

**Comment by vale981** [comment]
thank you very much for the hint.
I'll try it out :)

**Comment by mschneiderwng** [comment]
How is this applied? I tried

```
        poetryEnv = pkgs.poetry2nix.mkPoetryEnv {
          projectDir = ./.;
          overrides = pkgs.poetry2nix.overrides.withDefaults (final: prev: {
            matplotlib = prev.matplotlib.override { enableTk = true; };
          });
          editablePackageSources = {
            my-app = ./src;
          };
        };
```

and get the error

```
import _tkinter # If this fails your Python may not be configured for Tk
ModuleNotFoundError: No module named '_tkinter'
```

**Comment by adisbladis** [comment]
> How is this applied? I tried
> 
> ```
>         poetryEnv = pkgs.poetry2nix.mkPoetryEnv {
>           projectDir = ./.;
>           overrides = pkgs.poetry2nix.overrides.withDefaults (final: prev: {
>             matplotlib = prev.matplotlib.override { enableTk = true; };
>           });
>           editablePackageSources = {
>             my-app = ./src;
>           };
>         };
> ```
> 
> and get the error
> 
> ```
> import _tkinter # If this fails your Python may not be configured for Tk
> ModuleNotFoundError: No module named '_tkinter'
> ```

That does indicate that it is working, but you would also need to pass `python3Full` to `mkPoetryEnv` as the default python build doesn't enable tk.

**Comment by mschneiderwng** [comment]
I got the impression that the flags `enableTk` and `enableQt ` load the necessary packages with [these lines.](https://github.com/nix-community/poetry2nix/blob/b37a389df4977b9f9de1711297d732faaa73e648/overrides/default.nix#L855-L856)

At the moment, `enableTk` and `enableQt ` have no effect. Qt works if and only if I pass `pkgs.qt5.full` to `buildInputs` and Tk only works if I pass `pkgs.python3Full` to `buildInputs`. 

What is the purpose then of `enableTk` and `enableQt `?

**Comment by sepiabrown** [comment]
Changing the below code in `overrides/default.nix`
```
 matplotlib = super.matplotlib.overridePythonAttrs (
      old:
        let
          enableGhostscript = old.passthru.args.enableGhostscript or false;
```
into
```
 matplotlib = super.matplotlib.overridePythonAttrs (
      old:
        let
          enableGhostscript = old.passthru.args.enableGhostscript;
```
makes the `nix repl` moan the following.

`error: attribute 'enableGhostscript' missing`

**Comment by sepiabrown** [comment]
I found that when using `pkgs.poetry2nix.overrides.withDefaults`, if the python package you want to override is either in the file `overrides/default.nix` or `overrides/build-systems.json`, you cannot override with overrides that @adisbladis showed.

> This isn't at all obvious, but `passthru.args` is set to whatever is passed to the function that creates the derivation.
> 
> Matplotlib didn't look at `passthru.args`, but instead looked at `passthru`. This should be fixed in #516.
> 
> With this change you should be able to create an override looking something like:
> 
> ```
> matplotlib = super.matplotlib.override { enableTk = true; }
> ```

**Comment by AlexChalk** [comment]
This works for me: 
```
{ pkgs ? import <nixos> { } }:

pkgs.poetry2nix.mkPoetryEnv {
  projectDir = ./.;
  python = pkgs.python3Full;
  overrides = pkgs.poetry2nix.overrides.withDefaults (self: super: {
    matplotlib = super.matplotlib.overridePythonAttrs (
      old: {
        enableTk = true;
      }
    );
  });
}
```

**Comment by jicksaw** [comment]
`super.matplotlib.overridePythonAttrs` didn't work for me, though I'm using a flake. The derivation's attribute does change, but it doesn't affect `matplotlib`'s buildInputs. `super.matplotlib.override` does work.

There's separate error when using `enableTk`; The `pkgs.libX11` input isn't found. I'm guessing because it's a spliced package, and for some reason the spliced top-level packages aren't in the `pkgs` that's being evaluated. https://github.com/nix-community/poetry2nix/blob/3c92540611f42d3fb2d0d084a6c694cd6544b609/overrides/default.nix#L1481

Here's the poetry2nix flake template modified to use Qt instead:

```nix
{
  description = "Application packaged using poetry2nix";

  inputs = {
    flake-utils.url = "github:numtide/flake-utils";
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
    poetry2nix = {
      url = "github:nix-community/poetry2nix";
      inputs.nixpkgs.follows = "nixpkgs";
    };
  };

  outputs = { self, nixpkgs, flake-utils, poetry2nix }:
    flake-utils.lib.eachDefaultSystem (system:
      let
        # see https://github.com/nix-community/poetry2nix/tree/master#api for more functions and examples.
        pkgs = nixpkgs.legacyPackages.${system};
        inherit (poetry2nix.lib.mkPoetry2Nix { inherit pkgs; }) mkPoetryApplication overrides;
      in
      {
        packages = {
          myapp = mkPoetryApplication {
            projectDir = self;
            python = break pkgs.python3Full;
            overrides = overrides.withDefaults (self: super: {
              matplotlib = super.matplotlib.override (
                old: {
                  enableQt = true;
                }
              );
            });
          };
          default = self.packages.${system}.myapp;
        };

        devShells.default = pkgs.mkShell {
          inputsFrom = [ self.packages.${system}.myapp ];
          packages = [ pkgs.poetry ];

          # Setup QT_PLUGIN_PATH
          # Source: https://discourse.nixos.org/t/python-qt-woes/11808/2
          buildInputs = [
            pkgs.qt5.wrapQtAppsHook
            pkgs.makeWrapper
            pkgs.bashInteractive
          ];
          shellHook = ''
            bashdir=$(mktemp -d)
            makeWrapper "$(type -p bash)" "$bashdir/bash" "''${qtWrapperArgs[@]}"
            exec "$bashdir/bash"
          '';
        };
      });
}

```

**Comment by vale981** [comment]
I totally forgot that I ever opened that issue and recently "re-discovered" the solution.
For me, the original tip by @adisbladis works in a flake.

```nix
overrides = poetry2nix.overrides.withDefaults (final: prev: {
              matplotlib = with pkgs; prev.matplotlib.override (
                {
                  enableGtk3 = true;
                }
              );
            });
```
