### ISSUE TITLE
Question: what is the proper way to add build system to packages?

### ISSUE THREAD

**Issue by takeda** [nix-community/poetry2nix#532]
I have three packages right now:

- aws-error-utils
- prometheus-fastapi-instrumentator
- fastapi-restful

That depend on poetry (not poetry-core), but I recently noticed that overrides was now split into `build-systems.json` and `default.nix` which appears to hold the old overrides. It looks like the place to change would be `build-systems.json` but looks like this file is automatically generated. So should such change go to `overrides/default.nix`?

BTW: I noticed that recently the build process drastically slowed down compared to the past. Now it seems like there might be a minute or so of evaluating before the actual building starts. Is this something that is temporary?

**Comment by adisbladis** [comment]
> It looks like the place to change would be build-systems.json but looks like this file is automatically generated. So should such change go to overrides/default.nix?

This file is semi-automatically generated. It's additive, so adding something manually and re-running generation won't remove anything.
How could we document this to make it more clear?

> BTW: I noticed that recently the build process drastically slowed down compared to the past. Now it seems like there might be a minute or so of evaluating before the actual building starts. Is this something that is temporary?

That's most likely because of a mass-change of derivation hashes causing a bunch of binary cache lookups.
I would expect this to go away on it's own.

**Comment by takeda** [comment]
> How could we document this to make it more clear?

I think a `README.md` file inside `overrides` directory would do the job. You could also add a comment on top of `default.nix` to remind about it.

> That's most likely because of a mass-change of derivation hashes causing a bunch of binary cache lookups.
I would expect this to go away on it's own.

No, it's happening every time, but since I wrote it, I also run the code on a build machine and over there it appears to be fast. So I'm wondering if this might be something Mac specific (the build machine is on NixOS). Or there is some kind of speed regression introduced in nix 2.4.
