### ISSUE TITLE
error: infinite recursion encountered with minimal example

### ISSUE THREAD

**Issue by dnmiller** [nix-community/poetry2nix#538]
I'm getting the error message "error: infinite recursion encountered" when using poetry2nix. I've set up a minimal example here that reproduces the error: 

https://github.com/dnmiller/poetry2nix-error

Running `nix-shell` in the repo will fail. Including `colorconsole` and `flit-core` as dependencies seems to be the key to reproducing the error.

**Comment by layus** [comment]
The culprit is that you end-up with the following cycle:

```
"python3.9-flit-core-3.6.0"
"python3.9-setuptools-scm-6.3.2" 
"python3.9-tomli-2.0.0"
"python3.9-flit-core-3.6.0"
```

I have no idea how to break it ATM, but nixpkgs flit and flit-core do not have that issue. So it must be the way flit-core is generated by poetry2nix in this case that creates the loop.

**Comment by layus** [comment]
And I guess the culprit for the above is https://github.com/nix-community/poetry2nix/blob/9b601b8cd0f5545ddb0e6a36a01983aca17d9f2a/overrides/build-systems.json#L1212-L1214 that adds flit-core as a build dependency to tomli, creating a loop.

**Comment by layus** [comment]
If you want, you could play with overrides, with and without the default ones to strip that annoying line.
See https://github.com/nix-community/poetry2nix#api for more info. I will have to debug more later.

**Comment by layus** [comment]
Found it! (at least it evaluates)

(that is a change in poetry2nix source code)

```
diff --git a/mk-poetry-dep.nix b/mk-poetry-dep.nix
index 478946d..69da6a0 100644
--- a/mk-poetry-dep.nix
+++ b/mk-poetry-dep.nix
@@ -97,6 +97,9 @@ pythonPackages.callPackage
         "packaging"
         "six"
         "pyparsing"
+        "flit"
+        "flit-core"
+        "poetry-core"
       ];
       baseBuildInputs = lib.optional (! lib.elem name skipSetupToolsSCM) pythonPackages.setuptools-scm;
       format = if isDirectory || isGit || isUrl then "pyproject" else fileInfo.format;
```

**Comment by kirelagin** [comment]
Hm, for me the infinite recursion thing magically resolved after I bumped my nixpkgs pin. However now I am getting

```text
ModuleNotFoundError: No module named 'flit'
```

when it is building `pip`. There seems to be something weird going on here.

**Comment by kirelagin** [comment]
Ok, I’m stupid it’s building not `pip` but another package. Anyway, I think this issue is unrelated.
