### ISSUE TITLE
Hatchling missing?

### ISSUE THREAD

**Issue by NorfairKing** [nix-community/poetry2nix#605]
I see this error:

```
nix-shell
error: attribute 'hatchling' missing, at /nix/store/5wryb8bv33i7bn87rc41jscf2xsr5q92-poetry2nix-src/overrides/default.nix:27:71
(use '--show-trace' to show detailed location information)
```

This feels like an edge-case that could be documented.

**Comment by takeda** [comment]
@NorfairKing I believe you either need to manually update nixpkgs (hatchling was added recently). Perhaps adding hatchling as a dependency could also work, but the former way should be better.

**Comment by NorfairKing** [comment]
@takeda I have upgraded nixpkgs. Is it possible that `hatchling` is not in the `nixos-21.11` branch ?

**Comment by takeda** [comment]
Yeah it was added last month (I think) so I doubt it would be backported.

**Comment by NorfairKing** [comment]
@takeda can you show me the PR? Then I can ask for a backport.
It would be nice if `poetry2nix` would remain compatible with the most recent nixos release...

**Comment by takeda** [comment]
@NorfairKing It was part of this PR https://github.com/NixOS/nixpkgs/pull/162538 but it had few updates since then

**Comment by patryk4815** [comment]
![Zrzut ekranu 2022-05-6 o 18 27 00](https://user-images.githubusercontent.com/3074260/167173682-1bbb037b-1768-4ee7-b6d5-98e0ca0db756.png)
Hi. Is this issue related?

**Comment by takeda** [comment]
@patryk4815 it looks like it, this PR: https://github.com/NixOS/nixpkgs/pull/169926 should fix it, but for now you can just add hatch-vcs as a dependency (it can be a dev dependency)

**Comment by NorfairKing** [comment]
@patryk4815 Yes it is. @takeda Could this fix be backported to `nixos-21.11`?

**Comment by NorfairKing** [comment]
Trying to do the backport here, but running into issues here: https://github.com/NixOS/nixpkgs/pull/172205

**Comment by l0b0** [comment]
Thank you for the tip, @patryk4815! I got soupsieve to build with `hatch-vcs = "*"` and

```
soupsieve = super.soupsieve.overridePythonAttrs (
  old: {
    buildInputs = (old.buildInputs or [ ]) ++ [
      self.hatch-vcs
    ];
  }
);
```
