### ISSUE TITLE
remove-special-dependencies.sh hook reformats pyproject.toml, breaking Scipy.

### ISSUE THREAD

**Issue by SemMulder** [nix-community/poetry2nix#613]
### Describe the issue

The `remove-*-dependencies.sh` hooks reformat `pyproject.toml` without indentation. This breaks a [(pretty bad) parser in `scipy/tools/cythonize.py`](https://github.com/scipy/scipy/blob/3595b3947faacbedf76de4cb410e0a4210059117/tools/cythonize.py#L64). Which, in turn, breaks the build.

Adding a `-i` (i.e. indent) flag in [remove-special-dependencies.sh](https://github.com/nix-community/poetry2nix/blob/9927a08fd9537e86a7769b00ab7c231066ae1fb3/hooks/remove-special-dependencies.sh#L13) will most likely solve that.

Another approach could be to leave the pyproject.toml untouched if there are no special dependencies in it.

@cpcloud which approach would you prefer? (Assuming we want to fix this :wink:).

**Comment by adisbladis** [comment]
> This breaks a [(pretty bad) parser in scipy/tools/cythonize.py](https://github.com/scipy/scipy/blob/3595b3947faacbedf76de4cb410e0a4210059117/tools/cythonize.py#L64). Which, in turn, breaks the build.

That's hilariously terrible ^_^

I think we could just always indent the output. Would you mind creating a PR?

**Comment by SemMulder** [comment]
> Would you mind creating a PR?

I'd be happy to. I'm currently at work, will look at it later :).

**Comment by SemMulder** [comment]
@adisbladis opened a PR: #617!
