### ISSUE TITLE
Poetry 1.2.0b2

### ISSUE THREAD

**Issue by lelit** [nix-community/poetry2nix#681]
Is there a plan to update "vendored" poetry to 1.2.0b2?

I ask because I'm facing what seems a [resolver problem with poetry 1.1.13](https://github.com/python-poetry/poetry/discussions/5936), apparently already fixed in poetry 1.2.0b2, that is preventing upgrades in a poetry2nix environment I'm working.

While I was able to adapt the [nixpkgs expression](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/python-modules/poetry/default.nix) to 1.0.2b2, basically overriding some of its dependencies like
```nix
  cleo' = pypkgs.buildPythonPackage rec {
    pname = "cleo";
    version = "1.0.0a5";
    src = pypkgs.fetchPypi {
      inherit pname version;
      sha256 = "sha256-CXydDgMy/VPMifwR6wproDCeajkzwI97OFWFVUhpJdM=";
    };
    propagatedBuildInputs = [pypkgs.clikit];
    doCheck = false;
  };

  poetry-core' = pypkgs.poetry-core.overridePythonAttrs (old: rec {
    version = "1.1.0b2";
    src = fetchFromGitHub {
      owner = "python-poetry";
      repo = "poetry-core";
      rev = version;
      sha256 = "sha256-7H5J0S7euh3tZ6Ug70WOgMm7yIxDBpVCFztpGqv5VMs=";
    };
    doCheck = false;
  });

  poetry-plugin-export' = pypkgs.buildPythonPackage rec {
    pname = "poetry-plugin-export";
    version = "1.0.4";
    src = pypkgs.fetchPypi {
      inherit pname version;
      hash = "sha256-38i5sScXz/JP1fdDRs811Kz5eYHXCr7oX2LK6kFUGhs=";
    };
    nativeBuildInputs = [pypkgs.pythonRelaxDepsHook];
    pythonRemoveDeps = ["poetry"];
    buildInputs = [
      poetry-core'
    ];
    doCheck = false;
  };
```
and little else, my Nix knowledge was not enough of update poetry2nix `pkgs/poetry`.

Thanks for any feedback.

**Comment by lelit** [comment]
Wrt to the problem that originated the request, I [tracked down](https://github.com/python-poetry/poetry/discussions/5936#discussioncomment-3113135) the problem to `poetry-core` 1.0.x

**Comment by takeda** [comment]
About 12 hours ago a patch was merged that updated poetry to version 1.1.14. I had also resolver problems, although it manifested differently.

Please note, that after I updated I still had the issue, until I purged caches (`poetry cache clear --all pypi`).

It looks like PyPI changed something in their API that broke poetry.

**Comment by lelit** [comment]
> Please note, that after I updated I still had the issue, until I purged caches (`poetry cache clear --all pypi`).

As explained in the referenced discussion, the problem is not related to the cache, nor to the recent fix against the API change.

**Comment by takeda** [comment]
Ah I see, nvm then.

**Comment by sepiabrown** [comment]
Have you tried [this](https://github.com/nix-community/poetry2nix/issues/345#issuecomment-897234333) in #345 ?

**Comment by lelit** [comment]
Thanks, I will give it a try

**Comment by adisbladis** [comment]
Poetry is being bumped to 1.2.0 in https://github.com/nix-community/poetry2nix/pull/704.
We're currently blocked on some required nixpkgs changes to hit the channels.
