### ISSUE TITLE
How to fix `error: Missing suitable source/wheel file entry for...`

### ISSUE THREAD

**Issue by arximboldi** [nix-community/poetry2nix#686]
### Describe the issue
Hi!

Thanks for this amazing project. I am having some issue however trying to get this to work properly.

I am working on a project where some libraries do have wheels/source metadata but some don't, and I get the infamous error of the form:
```
error: Missing suitable source/wheel file entry for autopep8
```

It seems that this metadata is sometimes added correctly when I introduce a new dependency with `poetry add ...`, however I do not seem to find a way to fixing the existing ones. I have tried:
```
rm poetry.lock
poetry install
```
But this actually generates a lock file with no source metadata at all! What is the best way to fix this issue? What is the correct workflow to avoid this issue across the whole team?

**Comment by arximboldi** [comment]
Ok, this may be this: https://github.com/python-poetry/poetry/issues/6045

**Comment by dpausp** [comment]
Had the same problem. Updating to the current poetry2nix revision with poetry 1.1.14, clearing the cache with `poetry cache clear pypi --all` and regenerating poetry.lock with `poetry lock` fixed it for me.

**Comment by takeda** [comment]
On one hand this issue should be closed as it isn't an issue with poetry2nix, on the other hand this report is very useful as the error is not clear what is happening or how to fix it.

Yes, this report helped me too.

**Comment by arximboldi** [comment]
Yes, sorry I didn't report back here! Upgrading `poetry` did it for me as well :)
