### ISSUE TITLE
torch fails in fixup phase

### ISSUE THREAD

**Issue by i077** [nix-community/poetry2nix#69]
When building a poetry environment with just `torch` in it, it builds and installs just fine, but in the fixup phase (when it sets RPATHS), it fails to find CUDA-related libraries, specifically `libcuda.so.1`.

---
Also related, this still happens if I add an override to `export USE_CUDA=0` in the `preConfigure` phase, probably because it just downloads a wheel anyways?

Also also related, `pandas`, which is a dependency of `torch`, wouldn't build without cython present, so I had to override the `nativeBuildInputs` to include cython:
```nix
pandas = super.pandas.overrideAttrs (old: {
  nativeBuildInputs = old.nativeBuildInputs ++ [ self.cython ];
});
```
---

Here are my [`pyproject.toml`](http://ix.io/2cWS) and [`poetry.lock`](http://ix.io/2cWT) files, and here is the [output of `nix-shell`](http://ix.io/2cWU).

If I add the below override to export `LD_LIBRARY_PATH` so it can find those libraries, I get one that I can't locate (`libcudart.so.10.1`).

```nix
(self: super: {
  torch = super.torch.overrideAttrs (old: {
    nativeBuildInputs = old.nativeBuildInputs
     ++ [ pkgs.cudatoolkit pkgs.linuxPackages.nvidia_x11 ];
    preConfigure = ''
      export LD_LIBRARY_PATH="${pkgs.linuxPackages.nvidia_x11}/lib:${pkgs.cudatoolkit}/targets/x86_64-linux/lib"
    '';
})
```
Output from running `nix-shell` with that is [here](http://ix.io/2cWX).

I'm not really sure where to go from here, or even if I'm going in the right direction.
I don't mind dropping the CUDA support when building pytorch, but like I said above exporting the proper variable doesn't affect it.

**Comment by adisbladis** [comment]
```
    torch = super.torch.overrideAttrs (old: let
      cudatoolkit = pkgs.cudatoolkit_10_1;
    in {
      buildInputs = old.buildInputs ++ [
        pkgs.linuxPackages.nvidia_x11
        cudatoolkit.lib
        cudatoolkit.out
        cudatoolkit.lib
        pkgs.nccl.dev
        pkgs.nccl.out
      ];
      preConfigure = ''
        export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:${cudatoolkit}/targets/x86_64-linux/lib"
      '';
    });
```
makes the package build, but fails at runtime with:
```
Python 3.7.6 (default, Dec 18 2019, 19:23:55) 
[GCC 9.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/nix/store/yvmslq2aig2iv9jxc527k2wzn6kf763r-python3.7-torch-1.4.0/lib/python3.7/site-packages/torch/__init__.py", line 81, in <module>
    from torch._C import *
ImportError: numpy.core.multiarray failed to import
```

**Comment by adisbladis** [comment]
All of these "data science" packages are an absolute horrific mess to get right :/

**Comment by i077** [comment]
Actually numpy wasn't available at all there. I had to `poetry add numpy` myself, which made torch import. Should it be added to `buildInputs` then?

**Comment by i077** [comment]
Just tested that out, adding numpy to `buildInputs` produced the same runtime import error. I guess I'll just stick with adding numpy alongside torch?

**Comment by energizah** [comment]
https://github.com/stites/pytorch-world apparently has built pytorch, maybe poetry2nix could use those expressions.

**Comment by timokau** [comment]
This override

```nix
torch = super.torch.overrideAttrs (old: let
  cudatoolkit = pkgs.cudatoolkit_10_1;
in {
  buildInputs = old.buildInputs ++ [
    pkgs.linuxPackages.nvidia_x11
    cudatoolkit.lib
    cudatoolkit.out
    cudatoolkit.lib
    pkgs.nccl.dev
    pkgs.nccl.out
  ];
  propagatedBuildInputs = [
    super.numpy
    super.future
  ];
  preConfigure = ''
    export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:${cudatoolkit}/targets/x86_64-linux/lib"
  '';
});
```

yields a working pytorch. See #187.
