### ISSUE TITLE
numpy fails because of cython

### ISSUE THREAD

**Issue by pmiddend** [nix-community/poetry2nix#698]
### Describe the issue
I've created a super simple test repository here: https://github.com/pmiddend/poetry2nix-numpy-test

The pyproject.toml contains just `numpy-1.22.4` as a dependency, the poetry2nix version is `1.31.0`. Building with `nix-build -A pythonPackage` fails with:

```
RuntimeError: Building NumPy requires Cython >= 0.29.30, found 0.29.28 at /nix/store/y0b6mgmhm1vhwpsymcypr3sm64vdyj3z-python3.10-Cython-0.29.28/lib/python3.10/site-packages/Cython/__init__.py
```

If I explicitly add the higher `cython` version to the `pyproject.toml`, it works.

**Comment by asymmetric** [comment]
@pmiddend this is because 0.29.28 is the version in the nixpkgs you're using.

You can override it with e.g.

```nix
            cython = prev.cython.overrideAttrs (_: _: {
              src = pkgs.pythonPackages.fetchPypi {
                pname = "Cython";
                version = "0.29.32";
                hash = "sha256-hzPPR1i3kwTypOOev6xekjQbzke8zrJsElQ5iy+MGvc=";
              };
            });
```

and add it to your `poetryOverrides`.

**Comment by cpcloud** [comment]
Closing, thanks for the solution @asymmetric!
