### ISSUE TITLE
Next release of Poetry includes breaking changes to lockfile format

### ISSUE THREAD

**Issue by sciyoshi** [nix-community/poetry2nix#730]
### Describe the issue
The next release of Poetry will include a breaking change to the lockfile format (https://github.com/python-poetry/poetry/pull/6393). See that PR for full details, but the short version is that `metadata.files` is gone and replaced by `package.files` for each package.

poetry2nix will need to become aware of the new format for it to work with lockfiles generated by newer versions of poetry.

**Comment by adisbladis** [comment]
This has been dealt with already.
