### ISSUE TITLE
there are many packages missing setuptools dependency

### ISSUE THREAD

**Issue by yihuang** [nix-community/poetry2nix#771]
### Describe the issue

Shall we add setuptools as native build inputs by default?

**Comment by dbaynard** [comment]
Perhaps not enough to reopen… but it would be great if `poetry2nix` could provide a helpful error message in this case?

**Comment by vincentbernat** [comment]
This is quite inconvenient to do a PR for each package. It seems to be an endless game and it makes difficult to use poetry2nix with arbitrary packages. Currently, there are 5000+ packages in the JSON file. It is unknown how many are missing. It would be nice to be able to have a global override function (always add `setuptools`).

FI, since I didn't find a better way, I am using this:

```nix
        poetry = pkgs.poetry2nix.mkPoetryPackages {
          projectDir = ./.;
          overrides = pkgs.poetry2nix.overrides.withDefaults (self: super: {
            pulumi-hcloud = super.pulumi-hcloud.overridePythonAttrs (old: {
              nativeBuildInputs = (old.nativeBuildInputs or [ ]) ++ [ self.setuptools ];
            });
          });
        };
```

**Comment by vincentbernat** [comment]
I am using this snippet to add missing setuptools dependency on "rare" package:
```nix
        pythonEnv = pkgs.poetry2nix.mkPoetryEnv {
          projectDir = ./.;
          overrides = pkgs.poetry2nix.overrides.withDefaults (self: super:
            (l.listToAttrs (l.map
            # Many dependencies need setuptools...
              (x: {
                name = x;
                value = super."${x}".overridePythonAttrs (old: {
                  nativeBuildInputs = (old.nativeBuildInputs or []) ++ [self.setuptools];
                });
              })
              ["commando" "fswrap" "pygments-haproxy" "pygments-ios" "pygments-junos" "hyde"]))
          );
        };
```
I don't think it scales to add them directly in poetry2nix (commando, fswrap and hyde are mostly dead projects, pygments-* are pet projects of mine). I don't even know how to fix them upstream. Is it a matter of adding a `pyproject.toml`? https://github.com/pypa/sampleproject/blob/main/pyproject.toml

**Comment by Atry** [comment]
See https://github.com/nix-community/poetry2nix/issues/1591

**Comment by TyberiusPrime** [comment]
Is there a technical, or a policy reason why we don't do this?
