### ISSUE TITLE
`preferWheel = true` ignored for package `panel`

### ISSUE THREAD

**Issue by asymmetric** [nix-community/poetry2nix#842]
### Describe the issue

Setting `preferWheel = true` in an override for `panel 0.14.1` doesn't result in the wheel been used, even though the package [has a wheel](https://pypi.org/project/panel/0.14.1/#files) and the Python version (3.9) matches.

The package then fails to build, as the build process for build tries to make network requests. 
### Additional context

[This repo](https://github.com/asymmetric/wheel-repro) is a repro test case.

**Comment by nrdxp** [comment]
I don't think is unique to just panel. As far as I can tell the `preferWheel` in an override just doesn't work at all. I have an application where one dependency fails to build using wheels and other fails without it, so since this override doesn't work I can't build the project at all.

**Comment by asymmetric** [comment]
@nrdxp check the linked PR, it likely fixes the issue you're having.
