### ISSUE TITLE
Provide underscore/hyphen aliases

### ISSUE THREAD

**Issue by jtrakk** [nix-community/poetry2nix#86]
Distributions named `foo-bar` are equivalent to `foo_bar`. So I often have to provide overrides

```
foo-bar = self.foo_bar
```
or 

```
foo_bar = self.foo-bar
```

Would it be possible for poetry2nix to automatically provide these aliases by default, without having to enumerate all of them?

**Comment by adisbladis** [comment]
No, it would result in collisions when overriding one but not the other.
It's better to use only the canonical pypi names.
