### ISSUE TITLE
Update version of poetry2nix available in nixpkgs.

### ISSUE THREAD

**Issue by super-secret-github-user** [nix-community/poetry2nix#960]
### Describe the issue
My package does not build. It reports: `trace: warning: Unknown cryptography version: '39.0.0'. Please update getCargoHash.`

I can see that the hash exists in [this file](https://github.com/nix-community/poetry2nix/blob/master/overrides/default.nix), on line 385.

### Additional context

I am using this flake:

```
{
  description = "A very basic flake";

  inputs = {
    nixpkgs.url = "github:nixos/nixpkgs/nixos-unstable";
    poetry2nix.url = "github:nix-community/poetry2nix";
    slap-cli = {
      url = "github:super-secret-github-user/slap";
      flake = false;
    };
    krakenw = {
      url = "github:/helsing-ai/kraken-wrapper";
      flake = false;
    };
  };

  outputs =

  { self, nixpkgs, poetry2nix, slap-cli, krakenw }:
    let
      pkgs = nixpkgs.legacyPackages.x86_64-linux;
      shell =
      pkgs.mkShell
      {
        name = "kraken-wrapper";
        buildInputs = [
          (pkgs.poetry2nix.mkPoetryApplication {
            projectDir = krakenw.outPath;
          })
          (pkgs.poetry2nix.mkPoetryApplication {
            projectDir = slap-cli.outPath;
          })
        ];
      };
  in
  {
    devShells.x86_64-linux.default = shell;
  };
}
```

and running `nix flake check`.

How do I update the version of poetry2nix that nixpkgs uses?

**Comment by aou** [comment]
I couldn't figure it out either, so i slammed the whole `cryptography` override from the default overrides into my flake. super ugly but it worked, at least for my `mkPoetryEnv`. Apologies for the messy gist: https://gist.github.com/aou/0f1593f6fea3a456e6c1011ad404ee4c

**Comment by aou** [comment]
i should also mention, i think the most recent template has some differences from your example -- in your flake, it doesn't look like the poetry2nix input is used as all, instead it's using the one from nixpkgs. that being said, i still couldn't get mine to work, as i couldn't find the overrides in the poetry2nix input.

**Comment by super-secret-github-user** [comment]
apologies. The example is outdated. when using `poetry2nix:master` cryptography doesnt have the reported issue. At the time of testing, the nixpkgs poetry2nix did.

**Comment by theneosloth** [comment]
I'm still running into this using the flake template with wsl2. Is it possible to update the templates or provide instructions on how to overlay the right version?

`error: hash mismatch in fixed-output derivation '/nix/store/...-cryptography-39.0.1-vendor.tar.gz.drv':
         specified: sha256-AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=
            got:    sha256-0x+KIqJznDEyIUqVuYfIESKmHBWfzirPeX2R/cWlngc=`

As far as I can tell from the lock file this is pulling in the latest commit from master

**Comment by adisbladis** [comment]
Nixpkgs master has been bumped as of today.
