### ISSUE TITLE
fancycompleter, zipp, configparser: setup.py does not exist when preferWheels = true

### ISSUE THREAD

**Issue by mjlbach** [nix-community/poetry2nix#98]
I'm on master and noticed #62 was merged, however, I'm still getting the following error, but *only* when using `preferWheels = true;`:

```
patching sources
substitute(): ERROR: file 'setup.py' does not exist
builder for '/nix/store/9jcsf26k7qn39gyzr2agivmlsjsp7rli-python3.7-fancycompleter-0.9.1.drv' failed with exit code 1
cannot build derivation '/nix/store/hm4bdg4ask5w9bhg3m8kihv0ma78xhzz-python3-3.7.7-env.drv': 1 dependencies couldn't be built
```

## minimal shell.nix ##
```
with import <nixpkgs> {};
let
  src = fetchFromGitHub {
    owner = "nix-community";
    repo = "poetry2nix";
    rev = "98df940936e09164fdf30f3348fc071403667074";
    sha256 = "163d72djp5z6459v964ij2qam4p2zw6xfjfh3b94qz8xyi2c3w15";
  };
in
  with import "${src.out}/overlay.nix" pkgs pkgs;
  let
    pythonEnv = poetry2nix.mkPoetryEnv {
      projectDir = ./.;
      preferWheels = true;
    };
  in
  mkShell {
    name = "test-environment";

    nativeBuildInputs = [
      pythonEnv
    ];

  }
```
## pyproject.toml ##
```
[tool.poetry]
name = "poetry2nixtest"
version = "0.1.0"
description = ""
authors = ["Michael Lingelbach <m.j.lbach@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.7"
pdbpp = "^0.10.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

```

**Comment by adisbladis** [comment]
This is because all overrides currently assume that you are building from source and are unconditionally applied.

I tried to remedy this in https://github.com/nix-community/poetry2nix/pull/103 but I think it ended up a bit too messy.
Maybe it is the correct solution but I'm not convinced yet.

**Comment by mjlbach** [comment]
Thanks for working on it. I think the ideal solution would be to allow overriding the global preferWheels, since one can always flag problematic packages for building from source.

**Comment by mtn** [comment]
Tangentially related: when I don't set `preferWheels=true`, my `nix-shell` invocation makes it much further but fails with:

```
collision between `/nix/store/qlbgib3646irg182w9lcnj44p7pifrwi-python3.7-tensorflow-2.2.0/bin/.tensorboard-wrapped' and `/nix/store/z0lw0qgk2cf5bkzvn5ba53a88i6ahqar-python3.7-tensorboard-2.2.2/bin/.tensorboard-wrapped'
builder for '/nix/store/ary6lavdawmh1bpi4rgprl5vk0ghcdxm-python3-3.7.6-env.drv' failed with exit code 25
```

This was from a minimal example with `tensorflow 2.2` as the only dependency. Did you also encounter this @mjlbach?

**Comment by mjlbach** [comment]
@mtn Are you using poetry2nix from master? I thought I fixed this in #120

**Comment by mtn** [comment]
That was it -- I was using an old commit. Thanks!

**Comment by mjlbach** [comment]
So, an update. Still really interested in an alternative to #103, but I've been doing python dev in nix again and have taken to just manually overriding the default handlers for the wheels that fail to build. The following works for my example (not useful to fixing the wheel issues generally, but maybe useful to others looking for workaround)

```
with import <nixpkgs> {};
let
  src = fetchFromGitHub {
      owner = "nix-community";
      repo = "poetry2nix";
      rev = "649c50051f458538cb6e64f1164fd5416bb53ddf";
      sha256 = "afFNLtBXXCXXRtB+n0Kb+pEqRg3kn+1sqk7N/YvB7+w=";
      fetchSubmodules = true;
  };
in
  with import "${src.out}/overlay.nix" pkgs pkgs;
  let
    pythonEnv = poetry2nix.mkPoetryEnv {
      projectDir = ./.;
      preferWheels = true;
      overrides = poetry2nix.overrides.withDefaults (self: super: { fancycompleter = super.fancycompleter.overridePythonAttrs (
        old: {
          postPatch = '''';
        }
      ); });
    };
  in
  mkShell {
    name = "test-environment";

    nativeBuildInputs = [
      pythonEnv
    ];

  }
~
~
```

**Comment by adisbladis** [comment]
I created an issue to distinguish overrides at https://github.com/nix-community/poetry2nix/issues/476.

I still think this is the only correct fix.

Let's close this issue since the real problem is much larger than the packages listed in this issue.
